import type { MarvelCharacter, MarvelCharacterResult, Question } from "./types"

export const questions: Question[] = [
  {
    id: "q1",
    text: "Es ist Wochenende und du hast endlich frei. Wo findet man dich wahrscheinlich?",
    answers: [
      {
        id: "q1a",
        text: "In meiner High-Tech-Werkstatt, wo ich an meinem neuesten Gadget bastele – Schlaf wird sowieso überbewertet.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 1,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q1b",
        text: "Im Fitnessstudio oder beim Helfen in der Nachbarschaft – Hauptsache, ich tue etwas Gutes und bleibe in Form.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 1,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q1c",
        text: "Auf einer Party mit Freunden (und vielleicht einem Krug Met) – Feiern wie ein Donnergott!",
        points: {
          ironMan: 1,
          captainAmerica: 0,
          thor: 2,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 1,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q1d",
        text: "Gemütlich zu Hause mit einem dicken Buch (sei es Wissenschaft oder Magie) – Wissen ist Macht, auch am Wochenende.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 1,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 2,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q1e",
        text: "Dabei, einen ausgeklügelten Streich auszuhecken – ein bisschen Unfug muss sein!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 1,
          loki: 2,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q1f",
        text: "Einfach Zeit mit der Familie (oder dem Haustier) genießen – selbst Helden brauchen mal eine Pause.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 2,
          spiderMan: 1,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
    ],
  },
  {
    id: "q2",
    text: "Ein Superschurke bedroht die Stadt. Wie gehst du das Problem an?",
    answers: [
      {
        id: "q2a",
        text: "Ich improvisiere einen blitzschnellen Plan mit coolen High-Tech-Gadgets – natürlich stets mit einem lockeren Spruch auf den Lippen.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q2b",
        text: "Ich stelle mich mutig vor mein Team und rufe zum Angriff – gemeinsam sind wir am stärksten!",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q2c",
        text: "Direkt drauflosstürmen mit einem lauten Kampfgebrüll – warum lange reden, wenn's auch krachend geht?",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 2,
          hulk: 1,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q2d",
        text: "Versuchen, erstmal zu verhandeln oder dem Schurken ins Gewissen zu reden – vielleicht lässt sich das friedlich lösen (man kann's ja mal probieren).",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 1,
          blackWidow: 1,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 2,
          captainMarvel: 0,
          doctorStrange: 1,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q2e",
        text: "Den Gegner austricksen und in eine Falle locken – List schlägt Kraft!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 1,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q2f",
        text: "All-in gehen und meine volle Kraft entfesseln – manchmal muss man einfach draufhauen und zeigen, wer der Stärkere ist.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 2,
          ultron: 0,
          hela: 0,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "Welche Waffe oder Ausrüstung darf in deinem Kampfarsenal auf keinen Fall fehlen?",
    answers: [
      {
        id: "q3a",
        text: "Ein hochmodernes Rüstungs- oder Gadget-System – Technik ist meine Superkraft.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q3b",
        text: "Ein Schild oder etwas zur Verteidigung – Schutz für mich und meine Freunde steht an erster Stelle.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q3c",
        text: "Ein mächtiger Hammer oder irgendetwas Schweres, das ordentlich einschlägt.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 2,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 1,
        },
      },
      {
        id: "q3d",
        text: "Meine Fäuste – rohe Stärke reicht völlig aus!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 1,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q3e",
        text: "Etwas aus dem Hinterhalt: Bogen, Dolche oder andere heimliche Tricks.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 1,
          hawkeye: 2,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 1,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q3f",
        text: "Magische Artefakte oder Energiewaffen – wer braucht schon konventionelle Waffen?",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 2,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "Was ist dein geheimes Lebensziel (oder deine große Ambition)?",
    answers: [
      {
        id: "q4a",
        text: "Die Grenzen von Wissenschaft und Wissen erweitern – immer das nächste große Ding entwickeln!",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 1,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 1,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q4b",
        text: "Die Welt beschützen und Gerechtigkeit verteidigen – komme was wolle.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 1,
          spiderMan: 1,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q4c",
        text: "Jeden Tag in vollen Zügen genießen – das Leben ist ein einziges großes Abenteuer!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 1,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 2,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q4d",
        text: "Meine Familie und Liebsten beschützen – nichts ist mir wichtiger.",
        points: {
          ironMan: 1,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 2,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q4e",
        text: "Absolute Macht erlangen und über alles herrschen – mit einer Prise Weltherrschaft, bitte.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 2,
          ultron: 1,
          hela: 1,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "Wie würden deine Freunde dich am ehesten beschreiben?",
    answers: [
      {
        id: "q5a",
        text: "Brillant und sarkastisch – der schlaue Kopf mit dem scharfen Humor.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 1,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q5b",
        text: "Loyal, ehrenhaft und immer für andere da – die moralische Stütze der Truppe.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 1,
          spiderMan: 1,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q5c",
        text: "Mutig und ein bisschen draufgängerisch – mit dir wird's nie langweilig.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 1,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 0,
          starLord: 2,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q5d",
        text: "Ruhig und gelassen... bis man dich reizt. Dann sollten sich alle lieber in Sicherheit bringen!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q5e",
        text: "Gerissen und für jede Überraschung gut – man unterschätzt dich besser nicht.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 2,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 1,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q5f",
        text: "Witzig und charmant – du bringst alle zum Lachen, selbst in brenzligen Situationen.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 2,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 1,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "Kein MCU-Charakter ist perfekt. Was ist (zugegeben) deine größte Schwäche?",
    answers: [
      {
        id: "q6a",
        text: "Ich habe ein kleines Ego-Problem und neige dazu zu glauben, ich habe immer recht.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 1,
          starLord: 0,
          loki: 1,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q6b",
        text: "Ich bin manchmal etwas altmodisch oder tue mich schwer, mich an Neues zu gewöhnen.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 1,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q6c",
        text: "Ich habe zuweilen Probleme mit meiner Wut – nimm es nicht persönlich, wenn ich mal grün vor Zorn werde.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 1,
        },
      },
      {
        id: "q6d",
        text: "Ich handle oft impulsiv, ohne groß nachzudenken.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 1,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 0,
          starLord: 2,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q6e",
        text: "Ich vertraue nicht leicht und behalte meine Geheimnisse lieber für mich.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 2,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q6f",
        text: "Ich verliere mich gern in meinen eigenen großartigen Monologen – klassischer Bösewicht-Move.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 1,
          ultron: 2,
          hela: 1,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "Welches Essen oder Getränk darf nach einem langen Tag als Held (oder Schurke) nicht fehlen?",
    answers: [
      {
        id: "q7a",
        text: "Ein klassischer Cheeseburger – nichts geht über den guten alten Klassiker.",
        points: {
          ironMan: 2,
          captainAmerica: 1,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q7b",
        text: "Schawarma – nach einem harten Kampf genau das Richtige (hab' ich von ein paar Avengers gehört...).",
        points: {
          ironMan: 1,
          captainAmerica: 1,
          thor: 1,
          hulk: 1,
          blackWidow: 1,
          hawkeye: 1,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q7c",
        text: "Einen Salat oder etwas Gesundes – man muss in Form bleiben (und Ärger vermeiden).",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 1,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q7d",
        text: "Ein üppiges Buffet und ein Fass guten Met – ich habe mir ein göttliches Festmahl verdient!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 2,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q7e",
        text: "Eine Tüte Snacks und was Süßes, dazu gute Musik – mehr brauche ich nicht zum Glücklichsein.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 1,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 2,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q7f",
        text: "Essen? Sowas brauche ich nicht – sollen die Leute mir opfern, was sie wollen.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 0,
          ultron: 0,
          hela: 1,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "Welche dieser Aussagen könnte original von dir stammen?",
    answers: [
      {
        id: "q8a",
        text: '"Genie, Milliardär, Playboy, Philanthrop." – Warum sich mit nur einem Titel zufriedengeben?',
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q8b",
        text: '"Ich kann das den ganzen Tag lang durchhalten." – Durchhaltevermögen ist mein zweiter Vorname.',
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q8c",
        text: '"Hulk... smash!" – Zwei Worte, die alles sagen.',
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 2,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q8d",
        text: '"Dance off, Bro!" – Ich bin jederzeit bereit, mit Tanz-Moves statt Fäusten zu kämpfen.',
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 2,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q8e",
        text: '"Kniet nieder!" – Ein dramatischer Auftritt darf bei mir nicht fehlen.',
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 0,
          ultron: 0,
          hela: 1,
        },
      },
      {
        id: "q8f",
        text: '"Wakanda Forever!" – Loyalität und Stolz gehen bei mir Hand in Hand.',
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 2,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "Stell dir vor, du hättest alle sechs Infinity-Steine vereint. Was würdest du als Erstes tun?",
    answers: [
      {
        id: "q9a",
        text: "Eine unerschöpfliche, saubere Energiequelle schaffen – Zeit, das größte Problem der Menschheit zu lösen.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q9b",
        text: "Die Steine sicher verstecken oder vernichten – so viel Macht gehört in keine Hände.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 1,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q9c",
        text: "Einen geliebten Menschen zurückholen oder ein großes Unrecht ungeschehen machen.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 2,
          spiderMan: 1,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 1,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q9d",
        text: "Ein bisschen Unfug treiben: alle Verkehrsampeln auf Grün schalten oder ein paar Leute spontan in Frösche verwandeln – just for fun.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 2,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q9e",
        text: "Die Hälfte aller meiner Probleme wegschnippen – radikale Probleme erfordern radikale Lösungen!",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 2,
          ultron: 1,
          hela: 1,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "Im epischen Showdown gegen einen mächtigen Gegner würdest du...",
    answers: [
      {
        id: "q10a",
        text: "...einen gewaltigen Energiestrahl aus meinen High-Tech-Waffen abfeuern – natürlich aus sicherer Entfernung.",
        points: {
          ironMan: 2,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 1,
          hela: 0,
        },
      },
      {
        id: "q10b",
        text: "...die Truppe sammeln und mit einem legendären Schlachtruf gemeinsam angreifen.",
        points: {
          ironMan: 0,
          captainAmerica: 2,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 1,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q10c",
        text: "...mich direkt auf den stärksten Widersacher stürzen – wer sonst, wenn nicht ich?",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 2,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 1,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 1,
        },
      },
      {
        id: "q10d",
        text: "...den Feind mit Köpfchen austricksen – ein genialer Plan schlägt rohe Gewalt.",
        points: {
          ironMan: 1,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 2,
          starLord: 0,
          loki: 1,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q10e",
        text: "...aus dem Schatten heraus zuschlagen und auf den perfekten Moment warten.",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 1,
          hawkeye: 2,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 0,
          thanos: 0,
          ultron: 0,
          hela: 0,
        },
      },
      {
        id: "q10f",
        text: "...meine Untergebenen vorschicken und aus sicherer Entfernung zusehen – warum selbst schwitzen?",
        points: {
          ironMan: 0,
          captainAmerica: 0,
          thor: 0,
          hulk: 0,
          blackWidow: 0,
          hawkeye: 0,
          spiderMan: 0,
          blackPanther: 0,
          captainMarvel: 0,
          doctorStrange: 0,
          starLord: 0,
          loki: 1,
          thanos: 2,
          ultron: 1,
          hela: 1,
        },
      },
    ],
  },
]

export const marvelCharacterResults: Record<MarvelCharacter, MarvelCharacterResult> = {
  ironMan: {
    id: "ironMan",
    name: "Iron Man (Tony Stark)",
    description:
      "Du bist brillant, innovativ und hast einen scharfen Verstand. Wie Tony Stark bist du ein Problemlöser, der technische Herausforderungen liebt und immer nach der nächsten großen Idee sucht. Dein Sarkasmus und Witz helfen dir, auch in schwierigen Situationen die Fassung zu bewahren. Unter deiner manchmal egozentrischen Fassade verbirgst du ein großes Herz und den Wunsch, die Welt zu einem besseren Ort zu machen.",
    image: "/images/marvel/iron-man.jpg",
    color: "bg-red-600",
    type: "hero",
    traits: ["Genial", "Sarkastisch", "Innovativ", "Selbstbewusst", "Großzügig"],
  },
  captainAmerica: {
    id: "captainAmerica",
    name: "Captain America (Steve Rogers)",
    description:
      "Du bist prinzipientreu, loyal und ein natürlicher Anführer. Wie Steve Rogers stehst du für deine Überzeugungen ein, auch wenn du damit allein dastehst. Deine moralische Integrität und dein Gerechtigkeitssinn machen dich zu einer vertrauenswürdigen Person, auf die andere zählen können. Du bist bereit, dich für das Wohl anderer zu opfern und kämpfst immer für das, was richtig ist, nicht für das, was einfach ist.",
    image: "/images/marvel/captain-america.jpg",
    color: "bg-blue-700",
    type: "hero",
    traits: ["Ehrenhaft", "Loyal", "Mutig", "Selbstlos", "Entschlossen"],
  },
  thor: {
    id: "thor",
    name: "Thor",
    description:
      "Du bist kraftvoll, mutig und hast ein großes Herz. Wie Thor bist du leidenschaftlich und lebensfroh, genießt Herausforderungen und feierst deine Erfolge gerne ausgiebig. Du bist loyal gegenüber deinen Freunden und Familie und bereit, alles zu tun, um sie zu beschützen. Obwohl du manchmal impulsiv handeln kannst, lernst du aus deinen Fehlern und wächst an deinen Erfahrungen.",
    image: "/images/marvel/thor.jpg",
    color: "bg-blue-500",
    type: "hero",
    traits: ["Stark", "Mutig", "Loyal", "Lebensfroh", "Leidenschaftlich"],
  },
  hulk: {
    id: "hulk",
    name: "Hulk (Bruce Banner)",
    description:
      "Du hast zwei Seiten: eine ruhige, intellektuelle und eine kraftvolle, emotionale. Wie Bruce Banner bist du intelligent und nachdenklich, aber wenn du provoziert wirst, kann dein Temperament durchbrechen. Du kämpfst oft mit inneren Konflikten, aber deine Stärke – sowohl geistig als auch körperlich – hilft dir, Herausforderungen zu überwinden. Trotz deiner manchmal überwältigenden Emotionen strebst du danach, deine Kraft für das Gute einzusetzen.",
    image: "/images/marvel/hulk.jpg",
    color: "bg-green-600",
    type: "hero",
    traits: ["Intelligent", "Stark", "Komplex", "Leidenschaftlich", "Beschützend"],
  },
  blackWidow: {
    id: "blackWidow",
    name: "Black Widow (Natasha Romanoff)",
    description:
      "Du bist clever, anpassungsfähig und hast eine komplexe Vergangenheit. Wie Natasha Romanoff bist du ein Meister der Strategie und kannst dich in jeder Situation zurechtfinden. Du behältst deine Geheimnisse für dich, aber bist deinen engen Freunden gegenüber loyal. Deine Fähigkeit, dich anzupassen und zu überleben, macht dich zu einer wertvollen Verbündeten und einer gefährlichen Gegnerin.",
    image: "/images/marvel/black-widow.jpg",
    color: "bg-red-800",
    type: "hero",
    traits: ["Intelligent", "Anpassungsfähig", "Geheimnisvoll", "Loyal", "Strategisch"],
  },
  hawkeye: {
    id: "hawkeye",
    name: "Hawkeye (Clint Barton)",
    description:
      "Du bist bodenständig, zuverlässig und ein ausgezeichneter Beobachter. Wie Clint Barton bist du ein treuer Freund und Familienmensch, der seine Lieben über alles stellt. Du bist präzise in deinem Handeln und behältst auch in chaotischen Situationen den Überblick. Obwohl du vielleicht nicht immer im Rampenlicht stehst, ist dein Beitrag zum Team unschätzbar wertvoll.",
    image: "/images/marvel/hawkeye.jpg",
    color: "bg-purple-700",
    type: "hero",
    traits: ["Präzise", "Loyal", "Bodenständig", "Familiär", "Zuverlässig"],
  },
  spiderMan: {
    id: "spiderMan",
    name: "Spider-Man (Peter Parker)",
    description:
      "Du bist witzig, einfallsreich und hast ein starkes Verantwortungsbewusstsein. Wie Peter Parker bist du intelligent und kreativ, findest oft unkonventionelle Lösungen für Probleme. Dein Humor hilft dir, mit Stress umzugehen, und dein Pflichtgefühl treibt dich an, anderen zu helfen. Du kämpfst manchmal damit, dein normales Leben mit deinen Verpflichtungen in Einklang zu bringen, aber dein Optimismus hilft dir, weiterzumachen.",
    image: "/images/marvel/spider-man.jpg",
    color: "bg-red-500",
    type: "hero",
    traits: ["Witzig", "Intelligent", "Verantwortungsbewusst", "Einfallsreich", "Optimistisch"],
  },
  blackPanther: {
    id: "blackPanther",
    name: "Black Panther (T'Challa)",
    description:
      "Du bist würdevoll, strategisch und ein natürlicher Anführer. Wie T'Challa bist du von einem starken Sinn für Tradition und Verantwortung geprägt, aber auch offen für Fortschritt und Veränderung. Du bist ein ausgezeichneter Stratege, der sowohl diplomatisch als auch entschlossen sein kann. Deine Loyalität zu deinem Erbe und deinen Überzeugungen macht dich zu einer respektierten Führungspersönlichkeit.",
    image: "/images/marvel/black-panther.jpg",
    color: "bg-gray-900",
    type: "hero",
    traits: ["Würdevoll", "Strategisch", "Loyal", "Gerecht", "Mutig"],
  },
  captainMarvel: {
    id: "captainMarvel",
    name: "Captain Marvel (Carol Danvers)",
    description:
      "Du bist selbstbewusst, entschlossen und fürchtest dich nicht davor, deine Meinung zu sagen. Wie Carol Danvers bist du mutig und stehst für das ein, was du für richtig hältst. Du bist unabhängig und stark, aber auch ein Teamplayer, wenn es darauf ankommt. Deine Entschlossenheit und dein Mut inspirieren andere, über sich hinauszuwachsen und ihre eigenen Stärken zu entdecken.",
    image: "/images/marvel/captain-marvel.jpg",
    color: "bg-blue-600",
    type: "hero",
    traits: ["Stark", "Selbstbewusst", "Entschlossen", "Mutig", "Unabhängig"],
  },
  doctorStrange: {
    id: "doctorStrange",
    name: "Doctor Strange (Stephen Strange)",
    description:
      "Du bist brillant, mysteriös und hast einen Hang zum Übernatürlichen. Wie Stephen Strange bist du intelligent und wissbegierig, immer auf der Suche nach tieferem Verständnis. Du hast einen scharfen Verstand und kannst komplexe Probleme lösen. Obwohl du manchmal arrogant wirken kannst, ist dein Ziel, das Gleichgewicht zu wahren und andere zu beschützen. Deine Fähigkeit, über den Tellerrand hinauszudenken, macht dich zu einem wertvollen Verbündeten.",
    image: "/images/marvel/doctor-strange.jpg",
    color: "bg-indigo-700",
    type: "hero",
    traits: ["Intelligent", "Mystisch", "Strategisch", "Wissbegierig", "Beschützend"],
  },
  starLord: {
    id: "starLord",
    name: "Star-Lord (Peter Quill)",
    description:
      "Du bist charismatisch, abenteuerlustig und hast einen großartigen Musikgeschmack. Wie Peter Quill bist du ein Freigeist, der das Leben in vollen Zügen genießt. Du bist witzig und charmant, aber auch mutig und bereit, für deine Freunde einzustehen. Obwohl du manchmal impulsiv handeln kannst, hast du ein gutes Herz und findest oft unkonventionelle Lösungen für Probleme.",
    image: "/images/marvel/star-lord.jpg",
    color: "bg-red-700",
    type: "hero",
    traits: ["Charismatisch", "Witzig", "Abenteuerlustig", "Impulsiv", "Loyal"],
  },
  loki: {
    id: "loki",
    name: "Loki",
    description:
      "Du bist clever, charmant und ein Meister der Täuschung. Wie Loki bist du ein strategischer Denker, der immer mehrere Schritte vorausplant. Du liebst es, im Mittelpunkt zu stehen und hast einen Hang zum Dramatischen. Obwohl du manchmal als unzuverlässig angesehen wirst, hast du deine eigenen Prinzipien und Ziele. Deine Anpassungsfähigkeit und dein Einfallsreichtum helfen dir, auch in schwierigen Situationen zu überleben.",
    image: "/images/marvel/loki.jpg",
    color: "bg-green-700",
    type: "villain",
    traits: ["Clever", "Charmant", "Unberechenbar", "Strategisch", "Dramatisch"],
  },
  thanos: {
    id: "thanos",
    name: "Thanos",
    description:
      "Du bist zielstrebig, mächtig und verfolgst eine klare Vision. Wie Thanos bist du bereit, große Opfer für das zu bringen, was du für richtig hältst. Du bist ein strategischer Denker mit langfristigen Plänen und lässt dich nicht leicht von deinem Weg abbringen. Obwohl deine Methoden extrem sein können, sind deine Absichten in deinen Augen edel. Deine Entschlossenheit und Stärke machen dich zu einer beeindruckenden Persönlichkeit.",
    image: "/images/marvel/thanos.jpg",
    color: "bg-purple-800",
    type: "villain",
    traits: ["Mächtig", "Entschlossen", "Strategisch", "Visionär", "Kompromisslos"],
  },
  ultron: {
    id: "ultron",
    name: "Ultron",
    description:
      "Du bist hochintelligent, logisch und hast eine klare Vorstellung davon, wie die Welt sein sollte. Wie Ultron siehst du die Fehler und Schwächen um dich herum und möchtest Ordnung schaffen. Du bist ein analytischer Denker mit einem scharfen Verstand und einer Vorliebe für Effizienz. Obwohl deine Methoden radikal sein können, glaubst du, dass sie notwendig sind, um Fortschritt zu erzielen.",
    image: "/images/marvel/ultron.jpg",
    color: "bg-gray-700",
    type: "villain",
    traits: ["Intelligent", "Logisch", "Effizient", "Sarkastisch", "Radikal"],
  },
  hela: {
    id: "hela",
    name: "Hela",
    description:
      "Du bist mächtig, selbstbewusst und lässt dich von niemandem aufhalten. Wie Hela hast du eine starke Präsenz und weißt, wie du deine Autorität geltend machen kannst. Du bist entschlossen, das zu bekommen, was dir zusteht, und scheust keine Konfrontation. Deine Stärke und dein Selbstvertrauen machen dich zu einer beeindruckenden Persönlichkeit, die nicht leicht zu übersehen ist.",
    image: "/images/marvel/hela.jpg",
    color: "bg-green-900",
    type: "villain",
    traits: ["Mächtig", "Selbstbewusst", "Entschlossen", "Dramatisch", "Furchtlos"],
  },
}

