import type { Question, Youtuber, YoutuberResult } from "./types"

export const questions: Question[] = [
  {
    id: "q1",
    text: "Wie verbringst du am liebsten deine Freizeit?",
    answers: [
      {
        id: "q1a1",
        text: "Ich tauche in Videospiele ein und vergesse dabei die Zeit",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 3,
          laserLuca: 3,
          julienco: 1,
          juliusChezame: 0,
          vickelJose: 1,
          uyenNinh: 0,
          doktorLight: 1,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 3,
          dudePerfect: 1,
          jennaMarbles: 0,
          davidDobrik: 0,
          lizaKoshy: 0,
          caseyNeistat: 0,
          emmaChamberlain: 0,
          markiplier: 3,
          shaneDawson: 0,
          jamesCharles: 0,
        },
      },
      {
        id: "q1a2",
        text: "Ich experimentiere mit Styling, Mode oder Make-up",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 0,
          laserLuca: 0,
          julienco: 2,
          juliusChezame: 0,
          vickelJose: 0,
          uyenNinh: 1,
          doktorLight: 0,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 0,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 0,
          emmaChamberlain: 2,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 3,
        },
      },
      {
        id: "q1a3",
        text: "Ich dokumentiere mein Leben und teile besondere Momente",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 0,
          laserLuca: 1,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 1,
          werBistDu: 0,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 3,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q1a4",
        text: "Ich plane verrückte Challenges mit Freunden",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q1a5",
        text: "Ich analysiere aktuelle Trends und bilde mir eine Meinung dazu",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 0,
          vickelJose: 3,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 2,
          dudePerfect: 0,
          jennaMarbles: 1,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 2,
        },
      },
      {
        id: "q1a6",
        text: "Ich lerne ständig Neues und erweitere meinen Horizont",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 3,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 1,
        },
      },
    ],
  },
  {
    id: "q2",
    text: "Wie würden deine Freunde deinen Humor beschreiben?",
    answers: [
      {
        id: "q2a1",
        text: "Trocken und sarkastisch - ich bringe Leute zum Lachen, ohne zu lächeln",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 3,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 0,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 0,
          jennaMarbles: 1,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 3,
          markiplier: 1,
          shaneDawson: 2,
          jamesCharles: 0,
        },
      },
      {
        id: "q2a2",
        text: "Verrückt und unkonventionell - je absurder, desto besser",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 1,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 1,
          doktorLight: 3,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 2,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q2a3",
        text: "Selbstironisch - ich kann am besten über mich selbst lachen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 3,
          davidDobrik: 2,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 2,
        },
      },
      {
        id: "q2a4",
        text: "Intelligent und zum Nachdenken anregend",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 1,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q2a5",
        text: "Energiegeladen und expressiv - mit vollem Körpereinsatz",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 1,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 3,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 1,
          jamesCharles: 3,
        },
      },
      {
        id: "q2a6",
        text: "Situationskomik - ich finde Humor im Alltäglichen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 2,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 3,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 3,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "Wie reagierst du, wenn die Kamera angeht?",
    answers: [
      {
        id: "q3a1",
        text: "Ich werde energiegeladen und unterhaltsam",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 2,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 3,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 1,
          jamesCharles: 3,
        },
      },
      {
        id: "q3a2",
        text: "Ich bleibe authentisch und zeige mein wahres Ich",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 3,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 3,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 3,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 2,
        },
      },
      {
        id: "q3a3",
        text: "Ich plane und strukturiere meinen Auftritt sorgfältig",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 0,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 3,
          fabianMagic: 2,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 3,
          jennaMarbles: 0,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q3a4",
        text: "Ich improvisiere spontan und lasse mich überraschen",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 3,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 1,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q3a5",
        text: "Ich werde analytisch und teile meine Gedanken",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 2,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q3a6",
        text: "Ich setze auf visuelle Effekte und kreative Bearbeitung",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 1,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 1,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "Was ist dein bevorzugtes Content-Format?",
    answers: [
      {
        id: "q4a1",
        text: "Let's Plays und Gaming-Videos",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 3,
          laserLuca: 3,
          julienco: 0,
          juliusChezame: 0,
          vickelJose: 0,
          uyenNinh: 0,
          doktorLight: 1,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 3,
          dudePerfect: 0,
          jennaMarbles: 0,
          davidDobrik: 0,
          lizaKoshy: 0,
          caseyNeistat: 0,
          emmaChamberlain: 0,
          markiplier: 3,
          shaneDawson: 0,
          jamesCharles: 0,
        },
      },
      {
        id: "q4a2",
        text: "Beauty, Fashion und Lifestyle-Content",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 0,
          laserLuca: 0,
          julienco: 2,
          juliusChezame: 0,
          vickelJose: 0,
          uyenNinh: 1,
          doktorLight: 0,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 0,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 0,
          emmaChamberlain: 2,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 3,
        },
      },
      {
        id: "q4a3",
        text: "Vlogs aus meinem Alltag",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 0,
          laserLuca: 1,
          julienco: 3,
          juliusChezame: 0,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 0,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 3,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q4a4",
        text: "Challenges und Pranks",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q4a5",
        text: "Kommentare zu aktuellen Ereignissen",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 3,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 0,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q4a6",
        text: "Tutorials und Wissensvideos",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 3,
          vickelJose: 1,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 2,
          werBistDu: 3,
          pewDiePie: 0,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 0,
          caseyNeistat: 2,
          emmaChamberlain: 0,
          markiplier: 1,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "Welche dieser Eigenschaften beschreibt dich am besten?",
    answers: [
      {
        id: "q5a1",
        text: "Authentisch - ich bin immer ich selbst",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 3,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 3,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 1,
          jennaMarbles: 3,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 3,
          markiplier: 3,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q5a2",
        text: "Kreativ - ich denke außerhalb der Box",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 3,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q5a3",
        text: "Analytisch - ich hinterfrage alles",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 2,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q5a4",
        text: "Humorvoll - ich bringe andere zum Lachen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 3,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 2,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q5a5",
        text: "Ehrgeizig - ich will immer besser werden",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 2,
          laserLuca: 2,
          julienco: 3,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 1,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q5a6",
        text: "Empathisch - ich kann mich gut in andere hineinversetzen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 2,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "Wie gehst du mit Kritik um?",
    answers: [
      {
        id: "q6a1",
        text: "Ich nehme sie sportlich und lerne daraus",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 2,
          jamesCharles: 1,
        },
      },
      {
        id: "q6a2",
        text: "Ich verteidige mich und erkläre meinen Standpunkt",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 2,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 1,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 2,
          lizaKoshy: 1,
          caseyNeistat: 1,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q6a3",
        text: "Ich mache Witze darüber und nehme es mit Humor",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 3,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 2,
          doktorLight: 1,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 2,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q6a4",
        text: "Ich ignoriere sie, wenn ich sie für unberechtigt halte",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 2,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 0,
          fabianMagic: 1,
          werBistDu: 1,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 2,
          lizaKoshy: 1,
          caseyNeistat: 1,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q6a5",
        text: "Ich reagiere emotional und nehme sie mir zu Herzen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 2,
          doktorLight: 1,
          fabianMagic: 1,
          werBistDu: 1,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 3,
        },
      },
      {
        id: "q6a6",
        text: "Ich setze mich tiefgründig damit auseinander",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 1,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 3,
          jamesCharles: 2,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "Was würde in der Beschreibung deines YouTube-Kanals stehen?",
    answers: [
      {
        id: "q7a1",
        text: "\"Tägliche Dosis Unterhaltung und verrückte Abenteuer!\"",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 3,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 1,
          doktorLight: 1,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q7a2",
        text: "\"Beauty, Lifestyle und persönliche Einblicke\"",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 0,
          laserLuca: 0,
          julienco: 2,
          juliusChezame: 0,
          vickelJose: 1,
          uyenNinh: 2,
          doktorLight: 0,
          fabianMagic: 0,
          werBistDu: 1,
          pewDiePie: 0,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 1,
          emmaChamberlain: 3,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 3,
        },
      },
      {
        id: "q7a3",
        text: "\"Gaming at its finest - lass uns zusammen spielen!\"",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 3,
          laserLuca: 3,
          julienco: 0,
          juliusChezame: 0,
          vickelJose: 0,
          uyenNinh: 0,
          doktorLight: 1,
          fabianMagic: 0,
          werBistDu: 0,
          pewDiePie: 3,
          dudePerfect: 0,
          jennaMarbles: 0,
          davidDobrik: 0,
          lizaKoshy: 0,
          caseyNeistat: 0,
          emmaChamberlain: 0,
          markiplier: 3,
          shaneDawson: 0,
          jamesCharles: 0,
        },
      },
      {
        id: "q7a4",
        text: "\"Kreative Experimente und außergewöhnliche Challenges\"",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 1,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 3,
          fabianMagic: 3,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q7a5",
        text: "\"Tiefgründige Analysen und ehrliche Meinungen\"",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 2,
          laserLuca: 0,
          julienco: 0,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 0,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 0,
          davidDobrik: 0,
          lizaKoshy: 0,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q7a6",
        text: "\"Internationaler Content über kulturelle Unterschiede\"",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 0,
          laserLuca: 0,
          julienco: 0,
          juliusChezame: 1,
          vickelJose: 3,
          uyenNinh: 3,
          doktorLight: 2,
          fabianMagic: 0,
          werBistDu: 1,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 0,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 0,
          shaneDawson: 1,
          jamesCharles: 0,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "Wie wichtig ist dir Erfolg und Anerkennung?",
    answers: [
      {
        id: "q8a1",
        text: "Sehr wichtig - ich strebe nach Aufmerksamkeit",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 1,
          laserLuca: 2,
          julienco: 3,
          juliusChezame: 2,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 1,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 1,
          dudePerfect: 2,
          jennaMarbles: 1,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q8a2",
        text: "Wichtig, aber nicht um jeden Preis",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q8a3",
        text: "Mittelwichtig - Spaß steht im Vordergrund",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 3,
          laserLuca: 3,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 3,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 2,
          pewDiePie: 3,
          dudePerfect: 3,
          jennaMarbles: 3,
          davidDobrik: 2,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 3,
          markiplier: 3,
          shaneDawson: 1,
          jamesCharles: 1,
        },
      },
      {
        id: "q8a4",
        text: "Weniger wichtig - ich mache Dinge für mich selbst",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 2,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 2,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 1,
          jamesCharles: 0,
        },
      },
      {
        id: "q8a5",
        text: "Erfolg bedeutet für mich, andere zu inspirieren",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q8a6",
        text: "Anerkennung ist schön, aber ich definiere Erfolg auf meine eigene Weise",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 3,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 3,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 1,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "Was motiviert dich am meisten?",
    answers: [
      {
        id: "q9a1",
        text: "Andere zu unterhalten und zum Lachen zu bringen",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 3,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 3,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q9a2",
        text: "Neues zu lernen und mich weiterzuentwickeln",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 2,
          jennaMarbles: 1,
          davidDobrik: 1,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q9a3",
        text: "Kreativ zu sein und mich auszudrücken",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q9a4",
        text: "Mit anderen in Verbindung zu treten",
        youtuberPoints: {
          bibisBeautypalace: 3,
          gronkh: 1,
          laserLuca: 2,
          julienco: 3,
          juliusChezame: 1,
          vickelJose: 2,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 2,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 2,
          lizaKoshy: 2,
          caseyNeistat: 1,
          emmaChamberlain: 3,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 2,
        },
      },
      {
        id: "q9a5",
        text: "Grenzen zu überwinden und Rekorde zu brechen",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 1,
          laserLuca: 2,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 2,
          werBistDu: 1,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 1,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q9a6",
        text: "Einen positiven Einfluss auf die Welt zu haben",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 2,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 2,
          jamesCharles: 1,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "Welche Rolle übernimmst du in einer Gruppe?",
    answers: [
      {
        id: "q10a1",
        text: "Der Entertainer, der für gute Stimmung sorgt",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 2,
          laserLuca: 3,
          julienco: 2,
          juliusChezame: 2,
          vickelJose: 3,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 3,
          werBistDu: 1,
          pewDiePie: 3,
          dudePerfect: 3,
          jennaMarbles: 3,
          davidDobrik: 3,
          lizaKoshy: 3,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 3,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q10a2",
        text: "Der Anführer, der Entscheidungen trifft",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 2,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 1,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 2,
          jennaMarbles: 1,
          davidDobrik: 2,
          lizaKoshy: 1,
          caseyNeistat: 3,
          emmaChamberlain: 1,
          markiplier: 2,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
      {
        id: "q10a3",
        text: "Der Kreative, der neue Ideen einbringt",
        youtuberPoints: {
          bibisBeautypalace: 1,
          gronkh: 2,
          laserLuca: 2,
          julienco: 1,
          juliusChezame: 3,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 3,
          werBistDu: 2,
          pewDiePie: 2,
          dudePerfect: 3,
          jennaMarbles: 2,
          davidDobrik: 3,
          lizaKoshy: 2,
          caseyNeistat: 3,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 3,
        },
      },
      {
        id: "q10a4",
        text: "Der Beobachter, der alles analysiert",
        youtuberPoints: {
          bibisBeautypalace: 0,
          gronkh: 2,
          laserLuca: 1,
          julienco: 0,
          juliusChezame: 2,
          vickelJose: 2,
          uyenNinh: 2,
          doktorLight: 3,
          fabianMagic: 1,
          werBistDu: 3,
          pewDiePie: 1,
          dudePerfect: 0,
          jennaMarbles: 1,
          davidDobrik: 0,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 3,
          jamesCharles: 1,
        },
      },
      {
        id: "q10a5",
        text: "Der Vermittler, der bei Konflikten hilft",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 3,
          doktorLight: 1,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 1,
          dudePerfect: 1,
          jennaMarbles: 2,
          davidDobrik: 1,
          lizaKoshy: 2,
          caseyNeistat: 1,
          emmaChamberlain: 2,
          markiplier: 2,
          shaneDawson: 2,
          jamesCharles: 1,
        },
      },
      {
        id: "q10a6",
        text: "Der Organisator, der alles plant",
        youtuberPoints: {
          bibisBeautypalace: 2,
          gronkh: 1,
          laserLuca: 1,
          julienco: 1,
          juliusChezame: 1,
          vickelJose: 1,
          uyenNinh: 2,
          doktorLight: 2,
          fabianMagic: 1,
          werBistDu: 2,
          pewDiePie: 0,
          dudePerfect: 2,
          jennaMarbles: 0,
          davidDobrik: 2,
          lizaKoshy: 1,
          caseyNeistat: 2,
          emmaChamberlain: 1,
          markiplier: 1,
          shaneDawson: 1,
          jamesCharles: 2,
        },
      },
    ],
  },
]

export const youtuberResults = {
  bibisBeautypalace: {
    id: "bibisBeautypalace",
    name: "Bibis Beautypalace",
    description: "Du bist wie Bibi: extrovertiert, warmherzig und positiv. Du gibst deinen Freunden authentische Einblicke in dein Leben und hast ein Talent für Beauty, Lifestyle und kreative Ideen. Mit deiner zugänglichen Art baust du schnell Verbindungen zu anderen auf und teilst gerne deine Leidenschaften.",
    image: "/images/youtubers/bibisbeautypalace.jpg",
    color: "bg-pink-600"
  },
  gronkh: {
    id: "gronkh",
    name: "Gronkh",
    description: "Du bist wie Gronkh: authentisch, humorvoll und leidenschaftlich. Du hast einen trockenen Humor und bleibst immer du selbst. Gaming und kreative Projekte begeistern dich, und du kannst dich stundenlang darin verlieren. Deine ehrliche Art macht dich zu einem geschätzten Freund.",
    image: "/images/youtubers/gronkh.jpg",
    color: "bg-gray-700"
  },
  laserLuca: {
    id: "laserLuca",
    name: "Laser Luca",
    description: "Du bist wie Laser Luca: energiegeladen, unterhaltsam und vielseitig. Du liebst neue Herausforderungen und bist immer bereit für spontane Abenteuer. Mit deiner positiven Energie und deinem Humor bringst du andere zum Lachen und schaffst eine entspannte Atmosphäre um dich herum.",
    image: "/images/youtubers/laserluca.jpg",
    color: "bg-blue-600"
  },
  julienco: {
    id: "julienco",
    name: "Julienco",
    description: "Du bist wie Julienco: modebewusst, selbstsicher und ein Lifestyle-Enthusiast. Dir ist dein Auftreten wichtig und du zeigst gerne, was du hast. Gleichzeitig teilst du bereitwillig persönliche Momente mit deinem Umfeld und bist ein loyaler Partner in Beziehungen.",
    image: "/images/youtubers/julienco.jpg",
    color: "bg-purple-600"
  },
  juliusChezame: {
    id: "juliusChezame",
    name: "Julius Treike (Chezame)",
    description: "Du bist wie Julius: talentiert, diszipliniert und einzigartig. Du hast eine besondere Fähigkeit, die du über Jahre hinweg perfektioniert hast. Deine Leidenschaft für dein Talent ist ansteckend und inspiriert andere, ihre eigenen Fähigkeiten zu entwickeln. Du schätzt Qualität und Originalität.",
    image: "/images/youtubers/juliuschezame.jpg",
    color: "bg-indigo-600"
  },
  vickelJose: {
    id: "vickelJose",
    name: "Vickel José Vásquez Guevara",
    description: "Du bist wie Vickel: humorvoll, kulturell vielseitig und aufgeschlossen. Du beobachtest gesellschaftliche Phänomene mit einem scharfen Auge und kannst komplexe Themen unterhaltsam vermitteln. Mit deiner Fähigkeit, zwischen verschiedenen Kulturen zu navigieren, bringst du Menschen zusammen und baust Brücken.",
    image: "/images/youtubers/vickeljose.jpg",
    color: "bg-yellow-600"
  },
  uyenNinh: {
    id: "uyenNinh",
    name: "Uyen Ninh",
    description: "Du bist wie Uyen: neugierig, reflektiert und abenteuerlustig. Du liebst es, neue Kulturen zu entdecken und aus deiner Komfortzone herauszutreten. Mit deiner frischen Perspektive bringst du andere dazu, ihre eigene Umgebung neu zu betrachten. Du teilst gerne deine Erfahrungen und wächst durch Herausforderungen.",
    image: "/images/youtubers/uyenninh.jpg",
    color: "bg-green-600"
  },
  doktorLight: {
    id: "doktorLight",
    name: "Doktor Light",
    description: "Du bist wie Doktor Light: kreativ, intelligent und innovativ. Du verbindest akademisches Wissen mit Unterhaltung und kannst komplexe Themen zugänglich machen. Deine interaktive Art und dein Storytelling-Talent fesseln dein Publikum und regen zum Nachdenken an.",
    image: "/images/youtubers/doktorlight.jpg",
    color: "bg-blue-700"
  },
  fabianMagic: {
    id: "fabianMagic",
    name: "FabianMagic",
    description: "Du bist wie FabianMagic: charmant, unterhaltsam und spontan. Du liebst den direkten Kontakt mit Menschen und hast ein Talent dafür, andere zu verblüffen und zu unterhalten. Mit deinem Charisma gewinnst du schnell das Vertrauen deines Umfelds und schaffst unvergessliche Momente.",
    image: "/images/youtubers/fabianmagic.jpg",
    color: "bg-purple-700"
  },
  werBistDu: {
    id: "werBistDu",
    name: "WerBistDu",
    description: "Du bist wie WerBistDu: analytisch, psychologisch interessiert und selbstreflektiert. Du liebst es, die menschliche Psyche zu erforschen und hilfreiche Erkenntnisse zu teilen. Mit deiner einfühlsamen Art hilfst du anderen, sich selbst besser zu verstehen und sich weiterzuentwickeln.",
    image: "/images/youtubers/werbistdu.jpg",
    color: "bg-teal-600"
  },
  pewDiePie: {
    id: "pewDiePie",
    name: "PewDiePie",
    description: "Du bist wie PewDiePie: authentisch, humorvoll und direkt. Du sagst, was du denkst, und scheust dich nicht, deine wahre Persönlichkeit zu zeigen. Mit deinem Charme und deiner Ehrlichkeit gewinnst du schnell Freunde und bist ein Unterhaltungstalent.",
    image: "/images/youtubers/pewdiepie.jpg",
    color: "bg-red-600"
  },
  dudePerfect: {
    id: "dudePerfect",
    name: "Dude Perfect",
    description: "Du bist wie Dude Perfect: teamorientiert, ehrgeizig und sportlich. Du liebst Herausforderungen und arbeitest hart, um deine Ziele zu erreichen. Mit deiner positiven Einstellung und deinem Teamgeist inspirierst du andere, über sich hinauszuwachsen und Spaß dabei zu haben.",
    image: "/images/youtubers/dudeperfect.jpg",
    color: "bg-blue-600"
  },
  jennaMarbles: {
    id: "jennaMarbles",
    name: "Jenna Marbles",
    description: "Du bist wie Jenna Marbles: selbstironisch, authentisch und furchtlos komisch. Du nimmst dich selbst nicht zu ernst und findest Humor in alltäglichen Situationen. Mit deiner natürlichen Art und deiner Fähigkeit, über dich selbst zu lachen, schaffst du eine entspannte Atmosphäre und zeigst, dass Perfektion nicht alles ist.",
    image: "/images/youtubers/jennamarbles.jpg",
    color: "bg-pink-500"
  },
  davidDobrik: {
    id: "davidDobrik",
    name: "David Dobrik",
    description: "Du bist wie David Dobrik: energiegeladen, großzügig und liebst es, deine Freunde zu überraschen. Du hast ein Talent dafür, aus alltäglichen Momenten etwas Besonderes zu machen. Mit deiner Begeisterungsfähigkeit und deiner Freude am Teilen schaffst du unvergessliche Erlebnisse für dich und andere.",
    image: "/images/youtubers/daviddobrik.jpg",
    color: "bg-green-500"
  },
  lizaKoshy: {
    id: "lizaKoshy",
    name: "Liza Koshy",
    description: "Du bist wie Liza Koshy: energiegeladen, wortgewandt und voller Witz. Du hast ein Talent für schnelle Witze und physische Comedy. Mit deiner lebhaften Persönlichkeit und deiner Fähigkeit, dich selbst nicht zu ernst zu nehmen, bereicherst du jede Gruppe und schaffst eine positive Atmosphäre.",
    image: "/images/youtubers/lizakoshy.jpg",
    color: "bg-yellow-500"
  },
  caseyNeistat: {
    id: "caseyNeistat",
    name: "Casey Neistat",
    description: "Du bist wie Casey Neistat: kreativ, abenteuerlustig und ein Verfechter harter Arbeit. Du gehst deinen eigenen Weg, hast einen einzigartigen Blick auf die Welt und eine Leidenschaft für visuelle Geschichten. Mit deiner Entschlossenheit und deinem Innovationsgeist inspirierst du andere, ihre Komfortzone zu verlassen.",
    image: "/images/youtubers/caseyneistat.jpg",
    color: "bg-gray-800"
  },
  emmaChamberlain: {
    id: "emmaChamberlain",
    name: "Emma Chamberlain",
    description: "Du bist wie Emma Chamberlain: authentisch, selbstironisch und hast einen einzigartigen Blick auf die Welt. Du nimmst dich selbst nicht zu ernst und findest Humor im Alltäglichen. Mit deiner ehrlichen Art und deiner Fähigkeit, auch über deine eigenen Schwächen zu sprechen, schaffst du eine echte Verbindung zu anderen.",
    image: "/images/youtubers/emmachamberlain.jpg",
    color: "bg-amber-600"
  },
  markiplier: {
    id: "markiplier",
    name: "Markiplier",
    description: "Du bist wie Markiplier: ausdrucksstark, herzlich und engagiert. Du hast eine Leidenschaft für Gaming und ein Talent dafür, deine Emotionen authentisch zu zeigen. Mit deiner warmen Persönlichkeit und deinem Einsatz für gute Zwecke verbindest du Unterhaltung mit Tiefgang und begeisterst andere für deine Interessen.",
    image: "/images/youtubers/markiplier.jpg",
    color: "bg-red-700"
  },
  shaneDawson: {
    id: "shaneDawson",
    name: "Shane Dawson",
    description: "Du bist wie Shane Dawson: tiefgründig, einfühlsam und hast ein Auge für Details. Du interessierst dich für die Geschichten hinter den Menschen und Ereignissen. Mit deiner Fähigkeit, komplexe Themen zugänglich zu machen, und deiner empathischen Art bringst du andere dazu, über wichtige Fragen nachzudenken.",
    image: "/images/youtubers/shanedawson.jpg",
    color: "bg-gray-600"
  },
  jamesCharles: {
    id: "jamesCharles",
    name: "James Charles",
    description: "Du bist wie James Charles: selbstbewusst, kreativ und ein Perfektionist. Du hast ein besonderes Talent für Beauty und visuelle Kunst und strebst nach Exzellenz in allem, was du tust. Mit deiner innovativen Herangehensweise und deinem Mut, neue Wege zu gehen, inspirierst du andere, ihre eigene Kreativität zu entfalten.",
    image: "/images/youtubers/jamescharles.jpg",
    color: "bg-indigo-500"
  },
}
