import type { Pokemon, PokemonResult, Question } from "./types"

export const questions: Question[] = [
  {
    id: "q1",
    text: "Wie verbringst du am liebsten ein freies Wochenende?",
    answers: [
      {
        id: "q1a",
        text: "Draußen in der Natur aktiv sein, wandern oder Sport treiben.",
        points: {
          pikachu: 3,
          relaxo: 0,
          bisasam: 1,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 3,
          arkani: 3, // Energetic fire type
          arceus: 1, // Majestic but not necessarily outdoorsy
          dragoran: 2, // Likes flying around
          enton: 0, // Prefers to avoid activity
          galoppa: 3, // Fast runner, loves being active
        },
      },
      {
        id: "q1b",
        text: "Mit Freunden und Familie zusammen sein, gemeinsam lachen und etwas unternehmen.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 2,
          schiggy: 3,
          arkani: 2, // Loyal and friendly
          arceus: 2, // Cares about others
          dragoran: 3, // Very friendly and helpful
          enton: 1, // Often confused in social settings
          galoppa: 1, // Independent
        },
      },
      {
        id: "q1c",
        text: "Mich in ein spannendes Buch, einen Film oder ein Videospiel vertiefen.",
        points: {
          pikachu: 1,
          relaxo: 1,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 0, // Too energetic for sitting still
          arceus: 3, // Wise and contemplative
          dragoran: 1, // Prefers action
          enton: 2, // Likes quiet time
          galoppa: 0, // Too energetic
        },
      },
      {
        id: "q1d",
        text: "Zu Hause entspannen, ein gemütliches Bad nehmen oder einfach nur die Ruhe genießen.",
        points: {
          pikachu: 0,
          relaxo: 3,
          bisasam: 2,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 1, // Can be majestic and calm
          arceus: 2, // Peaceful
          dragoran: 2, // Gentle giant
          enton: 3, // Loves to relax
          galoppa: 0, // Too fiery to relax
        },
      },
    ],
  },
  {
    id: "q2",
    text: "Was ist dir in einer Freundschaft am wichtigsten?",
    answers: [
      {
        id: "q2a",
        text: "Ehrlichkeit und Loyalität, auf die man sich immer verlassen kann.",
        points: {
          pikachu: 1,
          relaxo: 1,
          bisasam: 3,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 3,
          arkani: 3, // Known for loyalty
          arceus: 3, // Values integrity
          dragoran: 3, // Very loyal
          enton: 1, // Means well but unreliable
          galoppa: 2, // Loyal but independent
        },
      },
      {
        id: "q2b",
        text: "Spaß und gemeinsame Erlebnisse, die das Leben aufregend machen.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 2,
          schiggy: 1,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q2c",
        text: "Intellektueller Austausch und tiefgründige Gespräche über interessante Themen.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q2d",
        text: "Verständnis und Akzeptanz, ohne Vorurteile oder Erwartungen.",
        points: {
          pikachu: 1,
          relaxo: 3,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "Wie gehst du mit stressigen Situationen um?",
    answers: [
      {
        id: "q3a",
        text: "Ich packe das Problem direkt an und versuche, es so schnell wie möglich zu lösen.",
        points: {
          pikachu: 2,
          relaxo: 0,
          bisasam: 1,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q3b",
        text: "Ich suche Unterstützung bei anderen und versuche, die Situation gemeinsam zu meistern.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 2,
          glumanda: 1,
          mew: 1,
          evoli: 2,
          glurak: 1,
          mewtu: 1,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q3c",
        text: "Ich analysiere die Situation ruhig und überlege mir einen strategischen Plan.",
        points: {
          pikachu: 1,
          relaxo: 1,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q3d",
        text: "Ich versuche, mich abzulenken und die Situation erstmal auszublenden.",
        points: {
          pikachu: 0,
          relaxo: 3,
          bisasam: 1,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "Welche Art von Musik oder Filmen bevorzugst du?",
    answers: [
      {
        id: "q4a",
        text: "Energetische und actionreiche Genres, die mich motivieren und begeistern.",
        points: {
          pikachu: 3,
          relaxo: 0,
          bisasam: 0,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q4b",
        text: "Fröhliche und unterhaltsame Inhalte, die gute Laune verbreiten.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 2,
          evoli: 2,
          glurak: 1,
          mewtu: 2,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q4c",
        text: "Anspruchsvolle und tiefgründige Werke, die zum Nachdenken anregen.",
        points: {
          pikachu: 0,
          relaxo: 1,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q4d",
        text: "Ruhige und entspannende Klänge oder Filme, die Geborgenheit vermitteln.",
        points: {
          pikachu: 0,
          relaxo: 3,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "Wenn du ein neues Hobby beginnen könntest, welches wäre das?",
    answers: [
      {
        id: "q5a",
        text: "Etwas, das mich körperlich herausfordert, wie Klettern oder Tanzen.",
        points: {
          pikachu: 3,
          relaxo: 0,
          bisasam: 1,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q5b",
        text: "Etwas Kreatives, das ich mit anderen teilen kann, wie ein Musikinstrument spielen in einer Band.",
        points: {
          pikachu: 2,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 2,
          evoli: 2,
          glurak: 1,
          mewtu: 2,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q5c",
        text: "Etwas, bei dem ich mein Wissen erweitern kann, wie eine neue Sprache lernen oder mich in ein wissenschaftliches Thema vertiefen.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q5d",
        text: "Etwas Entspannendes und Meditatives, wie Yoga oder Gartenarbeit.",
        points: {
          pikachu: 0,
          relaxo: 3,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "Wie würdest du dich selbst in drei Worten beschreiben?",
    answers: [
      {
        id: "q6a",
        text: "Mutig, energiegeladen, entschlossen.",
        points: {
          pikachu: 2,
          relaxo: 0,
          bisasam: 0,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q6b",
        text: "Freundlich, gesellig, optimistisch.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 2,
          evoli: 2,
          glurak: 1,
          mewtu: 2,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q6c",
        text: "Neugierig, intelligent, bedacht.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q6d",
        text: "Ruhig, geduldig, harmoniebedürftig.",
        points: {
          pikachu: 0,
          relaxo: 3,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "Was ist dein Lieblingsort?",
    answers: [
      {
        id: "q7a",
        text: "Ein belebter Ort, an dem immer etwas los ist.",
        points: {
          pikachu: 3,
          relaxo: 0,
          bisasam: 0,
          glumanda: 2,
          mew: 1,
          evoli: 2,
          glurak: 2,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q7b",
        text: "Ein gemütlicher Ort, an dem ich mich mit meinen Liebsten wohlfühle.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 2,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q7c",
        text: "Ein Ort, der mich inspiriert und meine Kreativität anregt.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 1,
          glumanda: 2,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q7d",
        text: "Ein ruhiger Ort in der Natur, an dem ich abschalten kann.",
        points: {
          pikachu: 1,
          relaxo: 2,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "Welche Rolle nimmst du in einer Gruppe meistens ein?",
    answers: [
      {
        id: "q8a",
        text: "Den Anführer, der die Initiative ergreift und Entscheidungen trifft.",
        points: {
          pikachu: 2,
          relaxo: 0,
          bisasam: 0,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q8b",
        text: "Den Vermittler, der für gute Stimmung sorgt und Konflikte löst.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 2,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q8c",
        text: "Den Beobachter, der alles analysiert und durchdachte Beiträge liefert.",
        points: {
          pikachu: 1,
          relaxo: 3,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 3,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
      {
        id: "q8d",
        text: "Den Unterstützer, der im Hintergrund agiert und für Harmonie sorgt.",
        points: {
          pikachu: 1,
          relaxo: 2,
          bisasam: 3,
          glumanda: 0,
          mew: 1,
          evoli: 3,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "Was ist dir wichtiger: Erfolg oder Zufriedenheit?",
    answers: [
      {
        id: "q9a",
        text: "Erfolg, weil ich gerne meine Ziele erreiche und mich beweise.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 0,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q9b",
        text: "Zufriedenheit, weil mir das Wohlbefinden meiner Mitmenschen am Herzen liegt.",
        points: {
          pikachu: 2,
          relaxo: 3,
          bisasam: 1,
          glumanda: 1,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
      {
        id: "q9c",
        text: "Zufriedenheit, weil ich gerne neue Dinge lerne und mich weiterentwickle.",
        points: {
          pikachu: 1,
          relaxo: 1,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q9d",
        text: "Zufriedenheit, weil ich ein ausgeglichenes und friedliches Leben führen möchte.",
        points: {
          pikachu: 1,
          relaxo: 3,
          bisasam: 2,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 3,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "Wenn du ein Tier wärst, welches wärst du?",
    answers: [
      {
        id: "q10a",
        text: "Ein schnelles und wendiges Tier, das Abenteuer liebt.",
        points: {
          pikachu: 3,
          relaxo: 0,
          bisasam: 0,
          glumanda: 3,
          mew: 1,
          evoli: 2,
          glurak: 3,
          mewtu: 1,
          gengar: 1,
          schiggy: 2,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q10b",
        text: "Ein verspieltes und soziales Tier, das gerne in Gesellschaft ist.",
        points: {
          pikachu: 3,
          relaxo: 1,
          bisasam: 1,
          glumanda: 1,
          mew: 2,
          evoli: 2,
          glurak: 1,
          mewtu: 2,
          gengar: 2,
          schiggy: 3,
          arkani: 3,
          arceus: 1,
          dragoran: 2,
          enton: 0,
          galoppa: 3,
        },
      },
      {
        id: "q10c",
        text: "Ein kluges und aufmerksames Tier, das seine Umgebung genau beobachtet.",
        points: {
          pikachu: 1,
          relaxo: 0,
          bisasam: 2,
          glumanda: 1,
          mew: 3,
          evoli: 2,
          glurak: 1,
          mewtu: 3,
          gengar: 3,
          schiggy: 1,
          arkani: 1,
          arceus: 3,
          dragoran: 2,
          enton: 3,
          galoppa: 1,
        },
      },
      {
        id: "q10d",
        text: "Ein gemütliches und friedliches Tier, das gerne döst.",
        points: {
          pikachu: 1,
          relaxo: 3,
          bisasam: 2,
          glumanda: 0,
          mew: 1,
          evoli: 2,
          glurak: 0,
          mewtu: 1,
          gengar: 3,
          schiggy: 3,
          arkani: 0,
          arceus: 1,
          dragoran: 2,
          enton: 3,
          galoppa: 0,
        },
      },
    ],
  },
]

export const pokemonResults: Record<Pokemon, PokemonResult> = {
  pikachu: {
    id: "pikachu",
    name: "Pikachu",
    description:
      "Du bist energiegeladen, freundlich und gesellig wie Pikachu! Du liebst es, Zeit mit Freunden zu verbringen und neue Abenteuer zu erleben. Deine positive Energie ist ansteckend und du bringst gerne Freude in das Leben anderer. Du bist loyal und stehst deinen Freunden immer zur Seite, wenn sie dich brauchen. Manchmal kannst du auch ein bisschen schelmisch sein, aber das macht dich nur noch liebenswürdiger!",
    image: "/images/pokemon/pikachu.png",
    color: "bg-yellow-400",
    type: "Elektro",
  },
  relaxo: {
    id: "relaxo",
    name: "Relaxo",
    description:
      "Du bist entspannt, gemütlich und gelassen wie Relaxo! Du weißt, wie man das Leben genießt und schätzt die kleinen Freuden des Alltags. Ruhe und Komfort sind dir wichtig, und du verstehst die Kunst des Nichtstuns perfekt. Trotz deiner gemütlichen Art bist du ein verlässlicher Freund, auf den man zählen kann, wenn es darauf ankommt. Du nimmst das Leben, wie es kommt, und lässt dich nicht so leicht aus der Ruhe bringen.",
    image: "/images/pokemon/relaxo.png",
    color: "bg-blue-400",
    type: "Normal",
  },
  bisasam: {
    id: "bisasam",
    name: "Bisasam",
    description:
      "Du bist ausgeglichen, naturverbunden und fürsorglich wie Bisasam! Du schätzt Harmonie und ein friedliches Umfeld. Mit deiner ruhigen und besonnenen Art bist du oft der Fels in der Brandung für deine Freunde. Du hast eine tiefe Verbindung zur Natur und schätzt die Schönheit der Welt um dich herum. Deine fürsorgliche Art macht dich zu einem wertvollen Freund, der immer ein offenes Ohr für andere hat.",
    image: "/images/pokemon/bisasam.png",
    color: "bg-green-500",
    type: "Pflanze/Gift",
  },
  glumanda: {
    id: "glumanda",
    name: "Glumanda",
    description:
      "Du bist leidenschaftlich, ehrgeizig und willenstark wie Glumanda! Du hast ein feuriges Temperament und gibst immer alles, um deine Ziele zu erreichen. Herausforderungen siehst du als Chance, zu wachsen und stärker zu werden. Du bist mutig und scheust keine Konfrontation, wenn es nötig ist. Deine Entschlossenheit und dein Durchhaltevermögen sind bewundernswert und inspirieren andere, über sich hinauszuwachsen.",
    image: "/images/pokemon/glumanda.png",
    color: "bg-orange-500",
    type: "Feuer",
  },
  mew: {
    id: "mew",
    name: "Mew",
    description:
      "Du bist neugierig, intelligent und vielseitig wie Mew! Du liebst es, Neues zu entdecken und dein Wissen zu erweitern. Deine Kreativität und deine Anpassungsfähigkeit helfen dir, in verschiedenen Situationen zu glänzen. Du bist verspielt und siehst das Leben als ein großes Abenteuer voller Möglichkeiten. Deine geheimnisvolle Art macht dich für andere interessant, und deine Weisheit wird von vielen geschätzt.",
    image: "/images/pokemon/mew.png",
    color: "bg-pink-300",
    type: "Psycho",
  },
  evoli: {
    id: "evoli",
    name: "Evoli",
    description:
      "Du bist anpassungsfähig, vielseitig und voller Potenzial wie Evoli! Du kannst dich leicht an neue Situationen anpassen und findest in verschiedenen Umgebungen deinen Weg. Deine Stärke liegt in deiner Vielseitigkeit und deiner Fähigkeit, dich weiterzuentwickeln. Du bist freundlich, liebenswert und kommst mit den unterschiedlichsten Menschen gut zurecht. Deine Offenheit für Veränderungen und deine Bereitschaft, neue Wege zu gehen, machen dich zu einer besonderen Persönlichkeit.",
    image: "/images/pokemon/evoli.png",
    color: "bg-amber-600",
    type: "Normal",
  },
  glurak: {
    id: "glurak",
    name: "Glurak",
    description:
      "Du bist stark, selbstbewusst und beeindruckend wie Glurak! Du strahlst eine natürliche Autorität aus und übernimmst gerne die Führung. Mit deinem Charisma und deiner Entschlossenheit inspirierst du andere und gewinnst ihren Respekt. Du bist unabhängig und liebst die Freiheit, deine eigenen Entscheidungen zu treffen. Wenn du für etwas brennst, setzt du all deine Energie ein, um es zu erreichen. Deine Leidenschaft und dein Mut machen dich zu einer beeindruckenden Persönlichkeit.",
    image: "/images/pokemon/glurak.png",
    color: "bg-red-600",
    type: "Feuer/Flug",
  },
  mewtu: {
    id: "mewtu",
    name: "Mewtu",
    description:
      "Du bist tiefgründig, unabhängig und außergewöhnlich stark wie Mewtu! Du hast einen scharfen Verstand und analysierst Situationen gründlich, bevor du handelst. Du schätzt deine Unabhängigkeit und ziehst es oft vor, alleine zu arbeiten. Obwohl du manchmal distanziert wirken kannst, hast du ein tiefes Verständnis für die Welt um dich herum. Du hinterfragst bestehende Strukturen und suchst nach tieferen Wahrheiten. Deine Entschlossenheit und deine einzigartigen Fähigkeiten machen dich zu einer bemerkenswerten Persönlichkeit.",
    image: "/images/pokemon/mewtu.png",
    color: "bg-purple-600",
    type: "Psycho",
  },
  gengar: {
    id: "gengar",
    name: "Gengar",
    description:
      "Du bist geheimnisvoll, verspielt und hast einen einzigartigen Sinn für Humor wie Gengar! Du liebst es, andere zu überraschen und bringst gerne Aufregung in den Alltag. Hinter deiner schelmischen Fassade verbirgst du eine tiefgründige und nachdenkliche Seite. Du bist kreativ und findest oft unkonventionelle Lösungen für Probleme. Dein Charme und deine geheimnisvolle Aura ziehen andere an, und deine Gesellschaft ist nie langweilig. Du gehst deinen eigenen Weg und lässt dich nicht von gesellschaftlichen Erwartungen einschränken.",
    image: "/images/pokemon/gengar.png",
    color: "bg-purple-800",
    type: "Geist/Gift",
  },
  schiggy: {
    id: "schiggy",
    name: "Schiggy",
    description:
      "Du bist fröhlich, ausgeglichen und zuverlässig wie Schiggy! Du gehst das Leben mit einer positiven Einstellung an und findest auch in schwierigen Situationen einen Grund zum Lächeln. Du bist ein loyaler Freund, auf den man sich immer verlassen kann. Mit deiner ruhigen und besonnenen Art meisterst du Herausforderungen und bleibst auch unter Druck gelassen. Du bist anpassungsfähig und findest in verschiedenen Umgebungen deinen Weg. Deine Fröhlichkeit und deine Zuverlässigkeit machen dich zu einem geschätzten Freund und Begleiter.",
    image: "/images/pokemon/schiggy.png",
    color: "bg-blue-500",
    type: "Wasser",
  },
  arkani: {
    id: "arkani",
    name: "Arkani",
    description:
      "Du bist wie Arkani! Dieses legendäre Pokémon ist bekannt für seine Schönheit und Anmut. Genau wie Arkani besitzt du ein stolzes und majestätisches Auftreten. Deine Loyalität und dein Mut machen dich zu einem verlässlichen Partner und Freund. Deine innere Stärke und dein edles Wesen beeindrucken andere. Du bist schnell, entschlossen und hast ein warmes Herz.",
    image: "/images/pokemon/arkani.png",
    color: "bg-orange-600",
    type: "Feuer",
  },
  arceus: {
    id: "arceus",
    name: "Arceus",
    description:
      "Du bist Arceus! Als das Alpha-Pokémon strahlst du eine ruhige und neutrale Kraft aus. Du kümmerst dich tief um die Welt und ihre Bewohner und bist bekannt dafür, Großzügigkeit zu zeigen. Deine Weisheit und dein Wunsch nach Harmonie machen dich zu einer respektvollen und manchmal auch unnahbaren Persönlichkeit. Verrat oder Bedrohungen nimmst du jedoch sehr ernst.",
    image: "/images/pokemon/arceus.png",
    color: "bg-yellow-200",
    type: "Normal",
  },
  dragoran: {
    id: "dragoran",
    name: "Dragoran",
    description:
      "Du bist Dragoran! Dieses Drachen-Pokémon ist bekannt für sein freundliches und sanftes Wesen. Genau wie Dragoran bist du hilfsbereit und beschützend gegenüber deinen Freunden. Deine Güte und deine Fähigkeit, in schwierigen Situationen Ruhe zu bewahren, zeichnen dich aus. Trotz deiner Stärke und Macht bist du sanftmütig und liebevoll zu denen, die dir wichtig sind.",
    image: "/images/pokemon/dragoran.png",
    color: "bg-orange-300",
    type: "Drache/Flug",
  },
  enton: {
    id: "enton",
    name: "Enton",
    description:
      "Du bist wie Enton! Dieses Wasser-Pokémon wirkt oft verwirrt, aber es besitzt eine verborgene psychische Kraft. Genau wie Enton bist du vielleicht manchmal etwas unentschlossen, aber in dir schlummert ein großes Potenzial. Deine liebenswerte und manchmal tollpatschige Art macht dich sympathisch. Unter Stress kannst du überraschende Fähigkeiten entwickeln, die andere beeindrucken.",
    image: "/images/pokemon/enton.png",
    color: "bg-yellow-400",
    type: "Wasser",
  },
  galoppa: {
    id: "galoppa",
    name: "Galoppa",
    description:
      "Du bist Galoppa! Dieses Feuer-Pokémon ist bekannt für seine Geschwindigkeit und seinen Wettbewerbsgeist. Genau wie Galoppa bist du energiegeladen und liebst es, dich mit anderen zu messen. Deine Leidenschaft und dein unermüdlicher Einsatz zeichnen dich aus. Du bist immer in Bewegung, liebst die Freiheit und beeindruckst andere mit deiner Entschlossenheit und deinem Feuergeist.",
    image: "/images/pokemon/galoppa.png",
    color: "bg-red-500",
    type: "Feuer",
  },
}

