import {
  Question,
  CarBrandProfile,
  TestResult,
  CarBrand,
  CarBrandGroup,
  Answer,
} from "./types";

// Definiert die Fragen des Tests
export const questions: Question[] = [
  {
    id: 1,
    text: "Wie würdest du deinen perfekten Samstag beschreiben?",
    category: "lifestyle",
    answers: [
      {
        id: "a",
        text: "Ein Shoppingtrip in der Stadt, gefolgt von einem Besuch in einem angesagten Café",
        points: {
          Mini: 3,
          BMW: 2,
          "Mercedes-Benz": 2,
          Fiat: 2,
          Peugeot: 1,
          Volkswagen: 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Eine Wanderung in den Bergen oder ein Ausflug in die Natur",
        points: {
          Jeep: 3,
          Volvo: 2,
          Toyota: 2,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Mini: 0,
        },
      },
      {
        id: "c",
        text: "Zuhause entspannen, vielleicht etwas im Garten arbeiten",
        points: {
          Volkswagen: 3,
          Toyota: 2,
          Honda: 2,
          Opel: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Skoda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ein Besuch im Museum oder einer Kulturveranstaltung",
        points: {
          Audi: 3,
          "Mercedes-Benz": 2,
          Volvo: 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Mit Freunden abhängen und abends in Clubs feiern",
        points: {
          Fiat: 3,
          Mini: 2,
          Peugeot: 2,
          Renault: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Tüfteln und Basteln an einem persönlichen Projekt",
        points: {
          Honda: 3,
          Skoda: 2,
          Mazda: 2,
          Toyota: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Volkswagen: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 2,
    text: "Wie reagierst du, wenn dir jemand im Straßenverkehr die Vorfahrt nimmt?",
    category: "behavior",
    answers: [
      {
        id: "a",
        text: "Ich hupe und zeige deutlich meinen Unmut",
        points: {
          BMW: 3,
          Audi: 2,
          Porsche: 2,
          "Mercedes-Benz": 1,
          Mini: 0,
          Volkswagen: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Ich bleibe gelassen – solche Dinge passieren eben",
        points: {
          Toyota: 3,
          Honda: 2,
          Suzuki: 2,
          Skoda: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Volkswagen: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Ich mache eine mentale Notiz, um in Zukunft bei diesem Fahrzeugtyp besonders aufzupassen",
        points: {
          Volvo: 3,
          Tesla: 2,
          Mazda: 2,
          Hyundai: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ich schüttele nur den Kopf und fahre weiter",
        points: {
          Ford: 3,
          Opel: 2,
          Renault: 2,
          Peugeot: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Fiat: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Ich versuche zu verstehen, warum die Person so gehandelt hat",
        points: {
          "Mercedes-Benz": 3,
          Audi: 2,
          Volvo: 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Ich überlege, ob mein Auto technisch überlegen genug ist",
        points: {
          Tesla: 3,
          Porsche: 2,
          BMW: 2,
          Audi: 1,
          Mini: 0,
          "Mercedes-Benz": 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 3,
    text: "Wofür gibst du am liebsten Geld aus?",
    category: "lifestyle",
    answers: [
      {
        id: "a",
        text: "Die neueste Technik und Gadgets",
        points: {
          Tesla: 3,
          Audi: 2,
          BMW: 2,
          "Mercedes-Benz": 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Qualitativ hochwertige Kleidung und Accessoires",
        points: {
          "Mercedes-Benz": 3,
          BMW: 2,
          Porsche: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Reisen und Erlebnisse",
        points: {
          Jeep: 3,
          Volvo: 2,
          Mazda: 2,
          Suzuki: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Hyundai: 0,
          Volkswagen: 0,
        },
      },
      {
        id: "d",
        text: "Mein Zuhause schöner machen",
        points: {
          Volvo: 3,
          Volkswagen: 2,
          Toyota: 2,
          Opel: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Sparen für langfristige Ziele",
        points: {
          Toyota: 3,
          Skoda: 2,
          Hyundai: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Praktische Dinge, die meinen Alltag erleichtern",
        points: {
          Honda: 3,
          Ford: 2,
          Opel: 2,
          Skoda: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Volkswagen: 0,
          Toyota: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 4,
    text: "Was ist dir bei einem Auto am wichtigsten?",
    category: "personality",
    answers: [
      {
        id: "a",
        text: "Zuverlässigkeit und niedrige Unterhaltskosten",
        points: {
          Toyota: 3,
          Skoda: 2,
          Hyundai: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Leistung und Fahrspaß",
        points: {
          BMW: 3,
          Porsche: 2,
          Mazda: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Komfort und Luxus",
        points: {
          "Mercedes-Benz": 3,
          Audi: 2,
          BMW: 2,
          Volvo: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Innovative Technologien",
        points: {
          Tesla: 3,
          Audi: 2,
          "Mercedes-Benz": 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Umweltfreundlichkeit",
        points: {
          Tesla: 3,
          Toyota: 2,
          Volvo: 2,
          Honda: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Volkswagen: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
          Skoda: 0,
        },
      },
      {
        id: "f",
        text: "Das Design und der Stil",
        points: {
          Porsche: 3,
          Mazda: 2,
          Peugeot: 2,
          Mini: 1,
          BMW: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 5,
    text: "Wie würdest du deinen Kleidungsstil beschreiben?",
    category: "personality",
    answers: [
      {
        id: "a",
        text: "Klassisch und zeitlos",
        points: {
          "Mercedes-Benz": 3,
          Volvo: 2,
          Volkswagen: 2,
          Audi: 1,
          Mini: 0,
          BMW: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Sportlich und lässig",
        points: {
          BMW: 3,
          Jeep: 2,
          Mazda: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
        },
      },
      {
        id: "c",
        text: "Immer nach der neuesten Mode",
        points: {
          Mini: 3,
          Tesla: 2,
          Peugeot: 2,
          BMW: 1,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Funktional und praktisch",
        points: {
          Toyota: 3,
          Honda: 2,
          Skoda: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Individuell und außergewöhnlich",
        points: {
          Fiat: 3,
          Mini: 2,
          Peugeot: 2,
          Renault: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Schlicht und unauffällig",
        points: {
          Volkswagen: 3,
          Toyota: 2,
          Skoda: 2,
          Opel: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 6,
    text: "Welcher dieser Filme entspricht am ehesten deinem Geschmack?",
    category: "lifestyle",
    answers: [
      {
        id: "a",
        text: "Ein actionreicher Blockbuster",
        points: {
          BMW: 3,
          Porsche: 2,
          Jeep: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
        },
      },
      {
        id: "b",
        text: "Eine romantische Komödie",
        points: {
          Mini: 3,
          Fiat: 2,
          Peugeot: 2,
          Renault: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Ein tiefgründiges Drama",
        points: {
          "Mercedes-Benz": 3,
          Volvo: 2,
          Audi: 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ein inspirierender Dokumentarfilm",
        points: {
          Tesla: 3,
          Volvo: 2,
          Toyota: 2,
          Honda: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Ein skurriler Independent-Film",
        points: {
          Mazda: 3,
          Peugeot: 2,
          Fiat: 2,
          Mini: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Ein klassischer Filmklassiker",
        points: {
          "Mercedes-Benz": 3,
          Volkswagen: 2,
          Volvo: 2,
          Ford: 1,
          Mini: 0,
          BMW: 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 7,
    text: "Wie verhältst du dich auf einer Party?",
    category: "behavior",
    answers: [
      {
        id: "a",
        text: "Ich bin der Mittelpunkt und unterhalte die Gäste",
        points: {
          Mini: 3,
          BMW: 2,
          Fiat: 2,
          Porsche: 1,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Ich führe tiefgründige Gespräche mit wenigen Personen",
        points: {
          "Mercedes-Benz": 3,
          Volvo: 2,
          Audi: 2,
          Skoda: 1,
          Mini: 0,
          BMW: 0,
          Porsche: 0,
          Opel: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Ich beobachte lieber und halte mich im Hintergrund",
        points: {
          Volkswagen: 3,
          Toyota: 2,
          Hyundai: 2,
          Opel: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ich sorge dafür, dass alle eine gute Zeit haben",
        points: {
          Ford: 3,
          Honda: 2,
          Toyota: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Ich wechsle zwischen verschiedenen Gruppen hin und her",
        points: {
          Renault: 3,
          Mazda: 2,
          Peugeot: 2,
          Hyundai: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Volvo: 0,
          Tesla: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Ich diskutiere gerne über kontroverse Themen",
        points: {
          Tesla: 3,
          BMW: 2,
          Audi: 2,
          "Mercedes-Benz": 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 8,
    text: "Was wäre dein Traumurlaub?",
    category: "lifestyle",
    answers: [
      {
        id: "a",
        text: "Ein Abenteuerurlaub mit Outdoor-Aktivitäten",
        points: {
          Jeep: 3,
          Suzuki: 2,
          Toyota: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
        },
      },
      {
        id: "b",
        text: "Ein Strandurlaub zum Entspannen",
        points: {
          Fiat: 3,
          Mini: 2,
          Peugeot: 2,
          Renault: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Eine Kulturreise mit Museen und historischen Stätten",
        points: {
          "Mercedes-Benz": 3,
          Volvo: 2,
          Audi: 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ein Roadtrip durch unbekannte Gegenden",
        points: {
          Mazda: 3,
          BMW: 2,
          Porsche: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Luxuriöses Verwöhnen in einem 5-Sterne-Resort",
        points: {
          "Mercedes-Benz": 3,
          BMW: 2,
          Porsche: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Eine futuristische Smart City mit neuester Technologie erkunden",
        points: {
          Tesla: 3,
          Audi: 2,
          "Mercedes-Benz": 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 9,
    text: "Welches Tier entspricht am ehesten deiner Persönlichkeit?",
    category: "personality",
    answers: [
      {
        id: "a",
        text: "Löwe - majestätisch und selbstbewusst",
        points: {
          BMW: 3,
          Porsche: 2,
          "Mercedes-Benz": 2,
          Tesla: 1,
          Mini: 0,
          Volkswagen: 0,
          Audi: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "b",
        text: "Fuchs - schlau und anpassungsfähig",
        points: {
          Skoda: 3,
          Mazda: 2,
          Audi: 2,
          Hyundai: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Porsche: 0,
          Opel: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Biene - fleißig und teamorientiert",
        points: {
          Toyota: 3,
          Honda: 2,
          Ford: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Adler - weitblickend und unabhängig",
        points: {
          "Mercedes-Benz": 3,
          Volvo: 2,
          Tesla: 2,
          BMW: 1,
          Mini: 0,
          Volkswagen: 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Delfin - verspielt und intelligent",
        points: {
          Mini: 3,
          Fiat: 2,
          Honda: 2,
          Peugeot: 1,
          Volkswagen: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Ford: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Schildkröte - beständig und zuverlässig",
        points: {
          Volkswagen: 3,
          Toyota: 2,
          Volvo: 2,
          Opel: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
  {
    id: 10,
    text: "Wie gehst du mit neuen Herausforderungen um?",
    category: "behavior",
    answers: [
      {
        id: "a",
        text: "Ich stürze mich begeistert hinein und improvisiere",
        points: {
          Mini: 3,
          Fiat: 2,
          Jeep: 2,
          BMW: 1,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
        },
      },
      {
        id: "b",
        text: "Ich plane sorgfältig und gehe strukturiert vor",
        points: {
          "Mercedes-Benz": 3,
          Audi: 2,
          Volvo: 2,
          Toyota: 1,
          Mini: 0,
          BMW: 0,
          Volkswagen: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "c",
        text: "Ich hole mir Rat von Experten oder Freunden",
        points: {
          Skoda: 3,
          Toyota: 2,
          Honda: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "d",
        text: "Ich vertraue auf meine Erfahrung und Intuition",
        points: {
          BMW: 3,
          Porsche: 2,
          Mazda: 2,
          Audi: 1,
          Mini: 0,
          Volkswagen: 0,
          "Mercedes-Benz": 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Volvo: 0,
          Tesla: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
      {
        id: "e",
        text: "Ich suche nach innovativen, unkonventionellen Lösungen",
        points: {
          Tesla: 3,
          Mazda: 2,
          Peugeot: 2,
          Renault: 1,
          Mini: 0,
          BMW: 0,
          "Mercedes-Benz": 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Toyota: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Volvo: 0,
          Hyundai: 0,
          Suzuki: 0,
          Volkswagen: 0,
          Jeep: 0,
        },
      },
      {
        id: "f",
        text: "Ich wäge Risiken und Chancen genau ab",
        points: {
          Volvo: 3,
          "Mercedes-Benz": 2,
          Toyota: 2,
          Volkswagen: 1,
          Mini: 0,
          BMW: 0,
          Audi: 0,
          Porsche: 0,
          Opel: 0,
          Skoda: 0,
          Honda: 0,
          Ford: 0,
          Fiat: 0,
          Peugeot: 0,
          Renault: 0,
          Tesla: 0,
          Mazda: 0,
          Hyundai: 0,
          Suzuki: 0,
          Jeep: 0,
        },
      },
    ],
  },
];

// Definiert die Profile der Automarken
export const carBrandProfiles: Record<CarBrand, CarBrandProfile> = {
  Volkswagen: {
    name: "Volkswagen",
    group: "Deutsche Automarken",
    traits: ["praktisch", "verlässlich", "bodenständig"],
    description:
      "Du schätzt Qualität und Zuverlässigkeit, ohne protzig zu sein. Manchmal etwas konservativ, aber immer vertrauenswürdig. Du bist wie ein Volkswagen: solide, funktional und eine sichere Wahl für den Alltag.",
    animal: "Schildkröte",
    keywords: ["solide", "funktional", "beständig"],
  },
  BMW: {
    name: "BMW",
    group: "Deutsche Automarken",
    traits: ["dynamisch", "statusbewusst", "leistungsorientiert"],
    description:
      "Du liebst Präzision und Leistung. Deine Meinung teilst du gerne mit, auch wenn nicht jeder danach fragt. In Verkehrssituationen neigst du eher zu impulsiven Reaktionen.",
    animal: "Löwe",
    keywords: ["präzision", "leistung", "impulsiv"],
  },
  "Mercedes-Benz": {
    name: "Mercedes-Benz",
    group: "Deutsche Automarken",
    traits: ["elegant", "qualitätsbewusst", "traditionell"],
    description:
      "Du bevorzugst klassische Werte und legst Wert auf ein gediegenes Auftreten. Sicherheit steht für dich an erster Stelle. Du planst gerne voraus und gehst strukturiert vor.",
    animal: "Adler",
    keywords: ["gediegenes Auftreten", "strukturiert", "sicher"],
  },
  Audi: {
    name: "Audi",
    group: "Deutsche Automarken",
    traits: ["fortschrittlich", "technikaffin", "diskret anspruchsvoll"],
    description:
      "Du magst es, die vier Ringe zur Schau zu stellen, ohne zu prahlen. Vorsprung durch Technik ist dein Lebensmotto.",
    animal: "Fuchs",
    keywords: ["vorsprung", "technik", "diskret"],
  },
  Porsche: {
    name: "Porsche",
    group: "Deutsche Automarken",
    traits: ["leidenschaftlich", "perfektionistisch", "leistungsorientiert"],
    description:
      "Du gibst dich nur mit dem Besten zufrieden und liebst es, am Limit zu leben. Du hast einen ausgeprägten Sinn für Design und Stil.",
    animal: "Löwe",
    keywords: ["ausgeprägter Sinn", "limit", "design"],
  },
  Opel: {
    name: "Opel",
    group: "Deutsche Automarken",
    traits: ["pragmatisch", "wirtschaftlich", "unprätentiös"],
    description:
      "Du hast einen gesunden Menschenverstand und schätzt ein gutes Preis-Leistungs-Verhältnis. Du bist eher zurückhaltend und machst nicht viel Aufhebens um deine Person.",
    animal: "Biene",
    keywords: ["gesunder Menschenverstand", "preiswert", "zurückhaltend"],
  },
  Skoda: {
    name: "Skoda",
    group: "Deutsche Automarken",
    traits: ["intelligent", "rational", "humorvoll"],
    description:
      "Du bist überraschend schlau und findest kluge Lösungen, ohne viel Aufhebens zu machen. Studien zeigen, dass Skoda-Fahrer tatsächlich den höchsten durchschnittlichen IQ unter Autofahrern haben.",
    animal: "Fuchs",
    keywords: ["schlau", "kluge Lösungen", "IQ"],
  },
  Toyota: {
    name: "Toyota",
    group: "Deutsche Automarken",
    traits: ["verlässlich", "effizient", "umweltbewusst"],
    description:
      "Du setzt auf Langlebigkeit und praktische Lösungen. Zuverlässigkeit ist dir wichtiger als Aufmerksamkeit. Du planst langfristig und bist wie eine Biene – fleißig und teamorientiert.",
    animal: "Biene",
    keywords: ["langlebig", "praktisch", "teamorientiert"],
  },
  Honda: {
    name: "Honda",
    group: "Deutsche Automarken",
    traits: ["innovativ", "qualitätsbewusst", "individualistisch"],
    description:
      "Du hast einen eigenen Kopf und bevorzugst durchdachte Technik vor Modeerscheinungen. Du bist praktisch veranlagt und schätzt gut durchdachte Lösungen.",
    animal: "Delfin",
    keywords: ["eigenständig", "durchdacht", "praktisch"],
  },
  Ford: {
    name: "Ford",
    group: "Deutsche Automarken",
    traits: ["traditionsbewusst", "volksnah", "vielseitig"],
    description:
      "Du passt dich verschiedenen Situationen an und bist ein Teamplayer, der sich nicht in den Vordergrund drängt. Du schüttelst nur den Kopf bei rücksichtslosen Verkehrsteilnehmern und fährst weiter.",
    animal: "Biene",
    keywords: ["teamplayer", "rucksichtsvoll", "vielseitig"],
  },
  Fiat: {
    name: "Fiat",
    group: "Deutsche Automarken",
    traits: ["lebenslustig", "spontan", "stilbewusst"],
    description:
      "Du liebst das Leben, feierst gerne und nimmst nicht alles zu ernst. Dolce Vita ist dein Lebensmotto.",
    animal: "Delfin",
    keywords: ["lebenslustig", "spontan", "stilbewusst"],
  },
  Peugeot: {
    name: "Peugeot",
    group: "Deutsche Automarken",
    traits: ["kultiviert", "design-orientiert", "unkonventionell"],
    description:
      "Du hast einen besonderen Geschmack und legst Wert auf Ästhetik und Komfort. Dein Kleidungsstil ist individuell und außergewöhnlich.",
    animal: "Fuchs",
    keywords: ["besonderer Geschmack", "ästhetisch", "individuell"],
  },
  Renault: {
    name: "Renault",
    group: "Deutsche Automarken",
    traits: ["kreativ", "experimentierfreudig", "familienorientiert"],
    description:
      "Du probierst gerne Neues aus und denkst oft außerhalb der Box. Du bist wie ein Fuchs – schlau und anpassungsfähig.",
    animal: "Fuchs",
    keywords: ["kreativ", "experimentierfreudig", "anpassungsfähig"],
  },
  Volvo: {
    name: "Volvo",
    group: "Deutsche Automarken",
    traits: ["sicherheitsbewusst", "umweltfreundlich", "praktisch"],
    description:
      "Du planst vorausschauend und nimmst Verantwortung für dich und andere ernst. Du führst gerne tiefgründige Gespräche und interessierst dich für Kultur und Geschichte.",
    animal: "Adler",
    keywords: ["vorausschauend", "verantwortungsvoll", "kulturinteressiert"],
  },
  Tesla: {
    name: "Tesla",
    group: "Deutsche Automarken",
    traits: [
      "zukunftsorientiert",
      "technikbegeistert",
      "trendiges Umweltbewusstsein",
    ],
    description:
      "Du stehst gerne an der Spitze der Innovation und machst aus deinem Umweltbewusstsein ein Statement.",
    animal: "Löwe",
    keywords: [
      "zukunftsorientiert",
      "technikbegeistert",
      "trendiges Umweltbewusstsein",
    ],
  },
  Mazda: {
    name: "Mazda",
    group: "Deutsche Automarken",
    traits: [
      "individualistisch",
      "designorientiert",
      "fahrerlebnis-fokussiert",
    ],
    description:
      "Du gehst gerne eigene Wege und schätzt die Verbindung zwischen Mensch und Maschine. Du magst skurrile Independent-Filme und suchst nach innovativen, unkonventionellen Lösungen für Probleme.",
    animal: "Fuchs",
    keywords: [
      "individualistisch",
      "designorientiert",
      "fahrerlebnis-fokussiert",
    ],
  },
  Hyundai: {
    name: "Hyundai",
    group: "Deutsche Automarken",
    traits: ["aufstrebend", "pragmatisch", "modern"],
    description:
      "Du bist ambitioniert und hast dich vom Underdog zur respektierten Persönlichkeit entwickelt. Du beobachtest lieber und hältst dich im Hintergrund, bist aber durchaus anpassungsfähig.",
    animal: "Fuchs",
    keywords: ["aufstrebend", "ambitioniert", "anpassungsfähig"],
  },
  Suzuki: {
    name: "Suzuki",
    group: "Deutsche Automarken",
    traits: ["vielseitig", "kostenbewusst", "abenteuerlustig"],
    description:
      "Du findest praktische Lösungen für alle Lebenslagen und bleibst dabei bescheiden. Laut Studien haben Suzuki-Fahrer den zweithöchsten IQ unter Autofahrern.",
    animal: "Fuchs",
    keywords: ["praktisch", "bescheiden", "IQ"],
  },
  Mini: {
    name: "Mini",
    group: "Deutsche Automarken",
    traits: ["individualistisch", "trendig", "urban"],
    description:
      "Du liebst es, aus der Masse herauszustechen und zeigst deinen eigenwilligen Stil mit Charme. Auf Partys bist du gerne der Mittelpunkt und unterhaltest die Gäste.",
    animal: "Delfin",
    keywords: ["individualistisch", "trendig", "charme"],
  },
  Jeep: {
    name: "Jeep",
    group: "Deutsche Automarken",
    traits: ["abenteuerlustig", "freiheitsliebend", "robust"],
    description:
      "Du liebst die Herausforderung und gehst gerne eigene Wege, auch wenn sie holprig sind. Dein Traumurlaub ist ein Abenteuerurlaub mit vielen Outdoor-Aktivitäten.",
    animal: "Löwe",
    keywords: ["abenteuerlustig", "freiheitsliebend", "robust"],
  },
};

// Berechnet das Testergebnis
export function calculateResult(answers: Record<number, Answer>): TestResult {
  const scores: Record<CarBrand, number> = {
    Volkswagen: 0,
    BMW: 0,
    "Mercedes-Benz": 0,
    Audi: 0,
    Porsche: 0,
    Opel: 0,
    Skoda: 0,
    Toyota: 0,
    Honda: 0,
    Ford: 0,
    Fiat: 0,
    Peugeot: 0,
    Renault: 0,
    Volvo: 0,
    Tesla: 0,
    Mazda: 0,
    Hyundai: 0,
    Suzuki: 0,
    Mini: 0,
    Jeep: 0,
  };

  // Berechne Punktzahl für jede Marke
  Object.values(answers).forEach((answer: Answer) => {
    Object.entries(answer.points).forEach(([brand, points]) => {
      scores[brand as CarBrand] += points;
    });
  });

  // Finde die höchste Punktzahl
  const maxScore = Math.max(...Object.values(scores));

  // Finde die Marke mit der höchsten Punktzahl
  const winningBrand = Object.entries(scores).find(
    ([_, score]) => score === maxScore
  )![0] as CarBrand;

  // Berechne die prozentuale Übereinstimmung
  const maxPossibleScore = Object.keys(answers).length * 3; // Maximale Punktzahl pro Frage ist 3
  const matchPercentage = (maxScore / maxPossibleScore) * 100;

  // Finde alternative Marken (mit ähnlicher Punktzahl)
  const alternativeBrands = Object.entries(scores)
    .filter(([brand, score]) => score >= maxScore - 3 && brand !== winningBrand)
    .map(([brand, score]) => ({
      brand: brand as CarBrand,
      score,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  return {
    brand: winningBrand,
    score: maxScore,
    profile: carBrandProfiles[winningBrand],
    matchPercentage,
    alternativeBrands,
  };
}

// Hilfsfunktion zum Formatieren der Ergebnisse
export function formatResult(result: TestResult): string {
  return `Du bist am ehesten ein ${result.brand}-Typ!
${result.profile.description}

Deine Haupteigenschaften:
${result.profile.traits.join(", ")}

Dein Spirit Animal: ${result.profile.animal}

Übereinstimmung: ${Math.round(result.matchPercentage)}%

Alternative Marken die auch zu dir passen könnten:
${result.alternativeBrands
  .map(
    (alt) =>
      `- ${alt.brand} (${Math.round(
        (alt.score / result.score) * 100
      )}% Übereinstimmung)`
  )
  .join("\n")}
`;
}
