import type { DCCharacter, DCCharacterResult, Question } from "./types";

export const questions: Question[] = [
  {
    id: "q1",
    text: "Du bekommst über Nacht Superkräfte. Was tust du?",
    answers: [
      {
        id: "q1a",
        text: "Menschen retten!",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q1b",
        text: "Erstmal analysieren, was ich genau kann und wie es funktioniert.",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q1c",
        text: "Meinen Freunden vorführen und Spaß haben.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q1d",
        text: "Meinen Rivalen zeigen, wer jetzt der Boss ist.",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
      {
        id: "q1e",
        text: "Einen Plan schmieden, wie ich Herrscher der Welt werden kann.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 2,
          chaos: 1,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q2",
    text: "Wie sieht dein perfekter freier Tag aus?",
    answers: [
      {
        id: "q2a",
        text: "Ehrenamtlich arbeiten und anderen helfen.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 2,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q2b",
        text: "Abenteuer erleben und Adrenalin spüren.",
        points: {
          courage: 2,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q2c",
        text: "Lesen, lernen und über komplexe Probleme nachdenken.",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q2d",
        text: "Mit Freunden Spaß haben und lachen.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q2e",
        text: "Allein sein und Pläne schmieden.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 1,
          chaos: 0,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "Auf einer Party bist du...",
    answers: [
      {
        id: "q3a",
        text: "Der Entertainer, der alle zum Lachen bringt.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q3b",
        text: "Derjenige, der interessante Gespräche führt.",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q3c",
        text: "Eher im Hintergrund, beobachte die anderen.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q3d",
        text: "Derjenige, der für Ordnung sorgt und aufpasst, dass nichts aus dem Ruder läuft.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q3e",
        text: "Derjenige, der für Chaos sorgt und verrückte Dinge anstellt.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 1,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "Wie stehst du zu Regeln?",
    answers: [
      {
        id: "q4a",
        text: "Regeln sind wichtig und sollten eingehalten werden.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 2,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q4b",
        text: "Regeln sind wichtig, aber manchmal muss man sie brechen, um das Richtige zu tun.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q4c",
        text: "Ich mache meine eigenen Regeln.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 1,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q4d",
        text: "Regeln? Welche Regeln?",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "In einem Teamprojekt...",
    answers: [
      {
        id: "q5a",
        text: "Übernehme ich die Leitung und weise anderen Aufgaben zu.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 2,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q5b",
        text: "Bringe ich kreative Ideen ein und löse komplexe Probleme.",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q5c",
        text: "Erledige ich zuverlässig meinen Teil der Arbeit.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q5d",
        text: "Sorge ich für gute Stimmung und motiviere das Team.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q5e",
        text: "Warte ich ab und improvisiere, wenn nötig.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "Du stehst einem übermächtigen Gegner gegenüber. Was tust du?",
    answers: [
      {
        id: "q6a",
        text: "Ich stelle mich ihm mutig entgegen, egal wie die Chancen stehen.",
        points: {
          courage: 2,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q6b",
        text: "Ich analysiere seine Schwächen und schmiede einen Plan.",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q6c",
        text: "Ich versuche, ihn zu überzeugen und eine friedliche Lösung zu finden.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q6d",
        text: "Ich provoziere ihn mit Witz und Humor, um ihn aus der Fassung zu bringen.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q6e",
        text: "Ich schließe mich ihm an, wenn er mir ein gutes Angebot macht.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "Dein Freund will etwas Illegales tun. Du...",
    answers: [
      {
        id: "q7a",
        text: "Hältst ihn davon ab und erklärst ihm, warum es falsch ist.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 2,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q7b",
        text: "Überredest ihn zu einer besseren, legalen Alternative.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q7c",
        text: "Lässt ihn machen, ist ja sein Leben.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q7d",
        text: "Machst mit, klingt nach Spaß!",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
      {
        id: "q7e",
        text: "Rufst die Polizei, Gesetz ist Gesetz.",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 2,
        },
      },
      {
        id: "q7f",
        text: "Hilfst ihm – gegen eine angemessene Bezahlung.",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "Wie würden dich deine Freunde beschreiben?",
    answers: [
      {
        id: "q8a",
        text: "Mutig und edel",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q8b",
        text: "Klug und strategisch",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q8c",
        text: "Witzig und charmant",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q8d",
        text: "Zuverlässig und gerecht",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 1,
        },
      },
      {
        id: "q8e",
        text: "Durchsetzungsfähig und bestimmt",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 1,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q8f",
        text: "Wild und unberechenbar",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "Was ist dein Lebensmotto?",
    answers: [
      {
        id: "q9a",
        text: "„Wahrheit und Gerechtigkeit siegen immer.“",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 1,
          leadership: 0,
          chaos: 0,
          justice: 2,
        },
      },
      {
        id: "q9b",
        text: '„Wissen ist Macht."',
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q9c",
        text: '„Hauptsache, Spaß."',
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q9d",
        text: '„Regeln sind da, um gebrochen zu werden."',
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
      {
        id: "q9e",
        text: '„Ohne Risiko kein Sieg."',
        points: {
          courage: 2,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q9f",
        text: '„Ich habe gern das Sagen."',
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 2,
          chaos: 0,
          justice: 0,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "Was wäre dein Traumjob?",
    answers: [
      {
        id: "q10a",
        text: "Polizist/in oder Richter/in",
        points: {
          courage: 1,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 2,
        },
      },
      {
        id: "q10b",
        text: "Wissenschaftler/in oder Forscher/in",
        points: {
          courage: 0,
          intelligence: 2,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q10c",
        text: "Komiker/in oder Schauspieler/in",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 2,
          morality: 0,
          leadership: 0,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q10d",
        text: "CEO eines großen Unternehmens",
        points: {
          courage: 0,
          intelligence: 1,
          humor: 0,
          morality: 0,
          leadership: 2,
          chaos: 0,
          justice: 0,
        },
      },
      {
        id: "q10e",
        text: "Extremsportler/in oder Stuntman/frau",
        points: {
          courage: 2,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 1,
          justice: 0,
        },
      },
      {
        id: "q10f",
        text: "Kein Bürojob – ich mache mein eigenes Ding",
        points: {
          courage: 0,
          intelligence: 0,
          humor: 0,
          morality: 0,
          leadership: 0,
          chaos: 2,
          justice: 0,
        },
      },
    ],
  },
];

export const dcCharacterResults: Record<DCCharacter, DCCharacterResult> = {
  superman: {
    id: "superman",
    name: "Superman",
    description:
      "Du bist mutig, moralisch und ein natürlicher Anführer. Wie Superman stehst du für Wahrheit, Gerechtigkeit und Hoffnung. Du bist bereit, dich für andere zu opfern und das Richtige zu tun, auch wenn es schwierig ist. Deine Stärke liegt nicht nur in deinen Fähigkeiten, sondern auch in deinem Charakter und deiner Integrität.",
    image: "/images/characters/dc/superman.jpeg",
    color: "bg-blue-700",
    type: "hero",
    traits: {
      courage: 10,
      intelligence: 7,
      humor: 3,
      morality: 10,
      leadership: 8,
      chaos: 1,
      justice: 10,
    },
  },
  batman: {
    id: "batman",
    name: "Batman",
    description:
      "Du bist intelligent, strategisch und entschlossen. Wie Batman nutzt du deinen Verstand und deine Ressourcen, um Probleme zu lösen und Gerechtigkeit zu bringen. Du bist diszipliniert und arbeitest hart, um deine Ziele zu erreichen. Obwohl du manchmal düster und zurückgezogen sein kannst, treibt dich ein starker Sinn für Gerechtigkeit an.",
    image: "/images/characters/dc/batman.jpeg",
    color: "bg-gray-900",
    type: "hero",
    traits: {
      courage: 9,
      intelligence: 9,
      humor: 1,
      morality: 8,
      leadership: 8,
      chaos: 1,
      justice: 9,
    },
  },
  wonderWoman: {
    id: "wonderWoman",
    name: "Wonder Woman",
    description:
      "Du bist mutig, mitfühlend und eine starke Führungspersönlichkeit. Wie Wonder Woman kämpfst du für Wahrheit und Gerechtigkeit mit Weisheit und Mitgefühl. Du bist ein Vorbild für andere und inspirierst sie, ihr Bestes zu geben. Deine Stärke liegt in deiner Fähigkeit, sowohl kraftvoll als auch einfühlsam zu sein.",
    image: "/images/characters/dc/wonderwoman.jpeg",
    color: "bg-red-700",
    type: "hero",
    traits: {
      courage: 10,
      intelligence: 8,
      humor: 4,
      morality: 9,
      leadership: 9,
      chaos: 2,
      justice: 9,
    },
  },
  flash: {
    id: "flash",
    name: "The Flash",
    description:
      "Du bist schnell, witzig und optimistisch. Wie The Flash bist du immer bereit zu helfen und findest oft kreative Lösungen für Probleme. Du bist loyal gegenüber deinen Freunden und Familie und bringst Leichtigkeit in schwierige Situationen. Deine Geschwindigkeit spiegelt sich in deiner schnellen Auffassungsgabe und deinem schnellen Humor wider.",
    image: "/images/characters/dc/flash.jpeg",
    color: "bg-red-600",
    type: "hero",
    traits: {
      courage: 7,
      intelligence: 8,
      humor: 10,
      morality: 8,
      leadership: 4,
      chaos: 4,
      justice: 8,
    },
  },
  aquaman: {
    id: "aquaman",
    name: "Aquaman",
    description:
      "Du bist stark, entschlossen und hast eine natürliche Autorität. Wie Aquaman bist du zwischen zwei Welten zu Hause und verstehst verschiedene Perspektiven. Du nimmst deine Verantwortung ernst, bist aber auch für Spaß zu haben. Deine Stärke liegt in deiner Fähigkeit, verschiedene Gruppen zu vereinen und für das einzustehen, was richtig ist.",
    image: "/images/characters/dc/aquaman.jpeg",
    color: "bg-yellow-600",
    type: "hero",
    traits: {
      courage: 9,
      intelligence: 6,
      humor: 7,
      morality: 7,
      leadership: 8,
      chaos: 3,
      justice: 7,
    },
  },
  cyborg: {
    id: "cyborg",
    name: "Cyborg",
    description:
      "Du bist intelligent, anpassungsfähig und resilient. Wie Cyborg nutzt du Technologie und Logik, um Probleme zu lösen. Du hast Herausforderungen überwunden und bist dadurch stärker geworden. Obwohl du manchmal mit deiner Identität kämpfst, nutzt du deine einzigartigen Fähigkeiten, um anderen zu helfen und die Welt zu einem besseren Ort zu machen.",
    image: "/images/characters/dc/cyborg.jpeg",
    color: "bg-gray-700",
    type: "hero",
    traits: {
      courage: 8,
      intelligence: 9,
      humor: 3,
      morality: 8,
      leadership: 5,
      chaos: 2,
      justice: 8,
    },
  },
  shazam: {
    id: "shazam",
    name: "Shazam",
    description:
      "Du bist enthusiastisch, optimistisch und hast ein großes Herz. Wie Shazam behältst du dir eine kindliche Begeisterung und Freude, auch wenn du erwachsene Verantwortung trägst. Du bist loyal gegenüber deinen Freunden und Familie und nutzt deine Fähigkeiten, um anderen zu helfen. Deine Stärke liegt in deiner Fähigkeit, das Beste in anderen zu sehen und sie zu inspirieren.",
    image: "/images/characters/dc/shazam.jpeg",
    color: "bg-red-600",
    type: "hero",
    traits: {
      courage: 6,
      intelligence: 5,
      humor: 9,
      morality: 8,
      leadership: 4,
      chaos: 6,
      justice: 7,
    },
  },
  supergirl: {
    id: "supergirl",
    name: "Supergirl",
    description:
      "Du bist mutig, optimistisch und entschlossen. Wie Supergirl bist du bereit, für das einzustehen, was richtig ist, und anderen zu helfen. Du bist loyal gegenüber deinen Freunden und Familie und lässt dich von Rückschlägen nicht unterkriegen. Deine Stärke liegt in deiner Fähigkeit, Hoffnung zu bewahren und andere zu inspirieren, auch in schwierigen Zeiten.",
    image: "/images/characters/dc/supergirl.jpeg",
    color: "bg-blue-600",
    type: "hero",
    traits: {
      courage: 9,
      intelligence: 7,
      humor: 6,
      morality: 9,
      leadership: 6,
      chaos: 3,
      justice: 9,
    },
  },
  greenLantern: {
    id: "greenLantern",
    name: "Green Lantern",
    description:
      "Du bist mutig, kreativ und willenstark. Wie Green Lantern nutzt du deine Vorstellungskraft und deinen Willen, um Herausforderungen zu meistern. Du bist entschlossen, das Richtige zu tun, und lässt dich von Angst nicht aufhalten. Deine Stärke liegt in deiner Fähigkeit, kreative Lösungen zu finden und für deine Überzeugungen einzustehen.",
    image: "/images/characters/dc/greenlantern.jpeg",
    color: "bg-green-700",
    type: "hero",
    traits: {
      courage: 10,
      intelligence: 6,
      humor: 7,
      morality: 8,
      leadership: 7,
      chaos: 4,
      justice: 8,
    },
  },
  martianManhunter: {
    id: "martianManhunter",
    name: "Martian Manhunter",
    description:
      "Du bist weise, einfühlsam und tiefgründig. Wie Martian Manhunter verstehst du die Gedanken und Gefühle anderer und nutzt dieses Verständnis, um zu helfen. Du bist ein ruhiger, aber effektiver Anführer, der andere durch Weisheit und Beispiel führt. Deine Stärke liegt in deiner Fähigkeit, verschiedene Perspektiven zu verstehen und als Brücke zwischen verschiedenen Gruppen zu dienen.",
    image: "/images/characters/dc/martianmanhunter.jpeg",
    color: "bg-green-800",
    type: "hero",
    traits: {
      courage: 8,
      intelligence: 9,
      humor: 3,
      morality: 9,
      leadership: 8,
      chaos: 1,
      justice: 9,
    },
  },
  blueBeetle: {
    id: "blueBeetle",
    name: "Blue Beetle",
    description:
      "Du bist anpassungsfähig, einfallsreich und optimistisch. Wie Blue Beetle findest du dich in neuen Situationen zurecht und nutzt deine Ressourcen kreativ. Du bist loyal gegenüber deinen Freunden und Familie und behältst deinen Humor auch in schwierigen Situationen. Deine Stärke liegt in deiner Fähigkeit, zu wachsen und zu lernen, während du Herausforderungen meisterst.",
    image: "/images/characters/dc/bluebeetle.jpeg",
    color: "bg-blue-600",
    type: "hero",
    traits: {
      courage: 7,
      intelligence: 6,
      humor: 8,
      morality: 9,
      leadership: 5,
      chaos: 4,
      justice: 8,
    },
  },
  joker: {
    id: "joker",
    name: "Joker",
    description:
      "Du bist chaotisch, unberechenbar und hast einen dunklen Sinn für Humor. Wie der Joker siehst du die Absurdität des Lebens und spielst nach deinen eigenen Regeln. Du bist kreativ und intelligent, nutzt diese Fähigkeiten aber oft für Chaos und Zerstörung. Deine Stärke liegt in deiner Fähigkeit, Konventionen zu durchbrechen und das Unerwartete zu tun.",
    image: "/images/characters/dc/joker.jpeg",
    color: "bg-purple-700",
    type: "villain",
    traits: {
      courage: 7,
      intelligence: 7,
      humor: 10,
      morality: 0,
      leadership: 6,
      chaos: 10,
      justice: 0,
    },
  },
  harleyQuinn: {
    id: "harleyQuinn",
    name: "Harley Quinn",
    description:
      "Du bist verspielt, unberechenbar und hast einen wilden Sinn für Humor. Wie Harley Quinn lebst du im Moment und folgst deinen Impulsen. Du bist loyal gegenüber denen, die du liebst, auch wenn diese Loyalität manchmal fehlgeleitet ist. Deine Stärke liegt in deiner Fähigkeit, dich anzupassen und weiterzumachen, egal wie schwierig die Umstände sind.",
    image: "/images/characters/dc/harleyquinn.jpeg",
    color: "bg-red-500",
    type: "villain",
    traits: {
      courage: 7,
      intelligence: 6,
      humor: 9,
      morality: 3,
      leadership: 4,
      chaos: 9,
      justice: 2,
    },
  },
  lexLuthor: {
    id: "lexLuthor",
    name: "Lex Luthor",
    description:
      "Du bist brillant, ehrgeizig und strategisch. Wie Lex Luthor nutzt du deinen Intellekt und deine Ressourcen, um deine Ziele zu erreichen. Du bist ein natürlicher Anführer mit einer klaren Vision, auch wenn diese Vision manchmal von Egoismus und Machtstreben geprägt ist. Deine Stärke liegt in deiner Fähigkeit, langfristig zu planen und Schwächen in anderen zu erkennen.",
    image: "/images/characters/dc/lexluthor.jpeg",
    color: "bg-green-600",
    type: "villain",
    traits: {
      courage: 3,
      intelligence: 10,
      humor: 4,
      morality: 0,
      leadership: 8,
      chaos: 2,
      justice: 1,
    },
  },
  blackAdam: {
    id: "blackAdam",
    name: "Black Adam",
    description:
      "Du bist mächtig, entschlossen und folgst deinem eigenen moralischen Kompass. Wie Black Adam bist du bereit, extreme Maßnahmen zu ergreifen, um das zu schützen, was du für wichtig hältst. Du bist ein starker Anführer mit klaren Überzeugungen, auch wenn diese manchmal im Konflikt mit konventioneller Moral stehen. Deine Stärke liegt in deiner Entschlossenheit und deinem unbeugsamen Willen.",
    image: "/images/characters/dc/blackadam.jpeg",
    color: "bg-yellow-800",
    type: "villain",
    traits: {
      courage: 10,
      intelligence: 7,
      humor: 2,
      morality: 4,
      leadership: 8,
      chaos: 3,
      justice: 6,
    },
  },
};
