import type { DogBreed, DogBreedResult, Question } from "./types";

export const questions: Question[] = [
  {
    id: "q1",
    text: "Wie aktiv bist du in deiner Freizeit?",
    answers: [
      {
        id: "q1a",
        text: "Sehr aktiv - ich jogge, wandere oder treibe täglich Sport.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 3,
          pug: 1,
          cavalierKingCharles: 2,
          shihTzu: 1,
          frenchBulldog: 1,
          goldenRetriever: 4,
          labradorRetriever: 4,
          irishWolfhound: 3,
          brusselsGriffon: 2,
          bullTerrier: 3,
          cotonDeTulear: 2,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q1b",
        text: "Aktiv - ich gehe regelmäßig spazieren und bewege mich gerne.",
        points: {
          borderCollie: 3,
          australianShepherd: 3,
          siberianHusky: 3,
          beagle: 5,
          pug: 3,
          cavalierKingCharles: 4,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 4,
          brusselsGriffon: 4,
          bullTerrier: 4,
          cotonDeTulear: 4,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q1c",
        text: "Mäßig aktiv - ich gehe gelegentlich spazieren, aber entspanne auch gerne zu Hause.",
        points: {
          borderCollie: 1,
          australianShepherd: 1,
          siberianHusky: 1,
          beagle: 3,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 3,
          brusselsGriffon: 5,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q1d",
        text: "Eher inaktiv - ich bevorzuge entspannte Aktivitäten zu Hause.",
        points: {
          borderCollie: 0,
          australianShepherd: 0,
          siberianHusky: 0,
          beagle: 1,
          pug: 4,
          cavalierKingCharles: 3,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 1,
          labradorRetriever: 1,
          irishWolfhound: 2,
          brusselsGriffon: 3,
          bullTerrier: 1,
          cotonDeTulear: 3,
          alaskanKleeKai: 1,
        },
      },
    ],
  },
  {
    id: "q2",
    text: "Wie viel Zeit kannst du täglich für die Pflege eines Hundes aufbringen?",
    answers: [
      {
        id: "q2a",
        text: "Weniger als 15 Minuten pro Tag.",
        points: {
          borderCollie: 1,
          australianShepherd: 0,
          siberianHusky: 0,
          beagle: 4,
          pug: 4,
          cavalierKingCharles: 1,
          shihTzu: 0,
          frenchBulldog: 5,
          goldenRetriever: 1,
          labradorRetriever: 3,
          irishWolfhound: 1,
          brusselsGriffon: 2,
          bullTerrier: 4,
          cotonDeTulear: 0,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q2b",
        text: "15-30 Minuten pro Tag.",
        points: {
          borderCollie: 3,
          australianShepherd: 2,
          siberianHusky: 2,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 3,
          shihTzu: 2,
          frenchBulldog: 4,
          goldenRetriever: 3,
          labradorRetriever: 5,
          irishWolfhound: 3,
          brusselsGriffon: 4,
          bullTerrier: 5,
          cotonDeTulear: 2,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q2c",
        text: "30-60 Minuten pro Tag.",
        points: {
          borderCollie: 5,
          australianShepherd: 4,
          siberianHusky: 4,
          beagle: 3,
          pug: 3,
          cavalierKingCharles: 5,
          shihTzu: 4,
          frenchBulldog: 2,
          goldenRetriever: 5,
          labradorRetriever: 4,
          irishWolfhound: 5,
          brusselsGriffon: 5,
          bullTerrier: 3,
          cotonDeTulear: 4,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q2d",
        text: "Mehr als eine Stunde pro Tag ist kein Problem.",
        points: {
          borderCollie: 4,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 2,
          pug: 1,
          cavalierKingCharles: 4,
          shihTzu: 5,
          frenchBulldog: 1,
          goldenRetriever: 4,
          labradorRetriever: 2,
          irishWolfhound: 4,
          brusselsGriffon: 3,
          bullTerrier: 2,
          cotonDeTulear: 5,
          alaskanKleeKai: 3,
        },
      },
    ],
  },
  {
    id: "q3",
    text: "Wie ist deine Wohnsituation?",
    answers: [
      {
        id: "q3a",
        text: "Wohnung ohne Garten.",
        points: {
          borderCollie: 0,
          australianShepherd: 0,
          siberianHusky: 0,
          beagle: 2,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 1,
          labradorRetriever: 1,
          irishWolfhound: 0,
          brusselsGriffon: 5,
          bullTerrier: 2,
          cotonDeTulear: 5,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q3b",
        text: "Wohnung mit Balkon oder Terrasse.",
        points: {
          borderCollie: 1,
          australianShepherd: 1,
          siberianHusky: 1,
          beagle: 3,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 2,
          labradorRetriever: 2,
          irishWolfhound: 0,
          brusselsGriffon: 5,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q3c",
        text: "Haus mit kleinem Garten.",
        points: {
          borderCollie: 3,
          australianShepherd: 3,
          siberianHusky: 3,
          beagle: 5,
          pug: 4,
          cavalierKingCharles: 4,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 4,
          labradorRetriever: 4,
          irishWolfhound: 2,
          brusselsGriffon: 4,
          bullTerrier: 5,
          cotonDeTulear: 4,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q3d",
        text: "Haus mit großem Garten oder ländliche Gegend.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 4,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 5,
          brusselsGriffon: 3,
          bullTerrier: 4,
          cotonDeTulear: 3,
          alaskanKleeKai: 4,
        },
      },
    ],
  },
  {
    id: "q4",
    text: "Wie wichtig ist dir ein gehorsamer, leicht trainierbarer Hund?",
    answers: [
      {
        id: "q4a",
        text: "Sehr wichtig - ich möchte einen Hund, der schnell lernt und gehorcht.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 2,
          beagle: 2,
          pug: 3,
          cavalierKingCharles: 4,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 3,
          brusselsGriffon: 3,
          bullTerrier: 2,
          cotonDeTulear: 4,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q4b",
        text: "Wichtig - Grundkommandos sollten kein Problem sein.",
        points: {
          borderCollie: 4,
          australianShepherd: 4,
          siberianHusky: 3,
          beagle: 3,
          pug: 4,
          cavalierKingCharles: 5,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 4,
          brusselsGriffon: 4,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q4c",
        text: "Nicht so wichtig - ein bisschen Eigensinn stört mich nicht.",
        points: {
          borderCollie: 2,
          australianShepherd: 2,
          siberianHusky: 4,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 3,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 5,
          brusselsGriffon: 5,
          bullTerrier: 5,
          cotonDeTulear: 3,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q4d",
        text: "Unwichtig - Hauptsache, der Hund ist liebenswert.",
        points: {
          borderCollie: 1,
          australianShepherd: 1,
          siberianHusky: 5,
          beagle: 4,
          pug: 5,
          cavalierKingCharles: 3,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 2,
          labradorRetriever: 2,
          irishWolfhound: 4,
          brusselsGriffon: 5,
          bullTerrier: 4,
          cotonDeTulear: 3,
          alaskanKleeKai: 4,
        },
      },
    ],
  },
  {
    id: "q5",
    text: "Wie empfindlich bist du gegenüber Hundegebell oder -geheul?",
    answers: [
      {
        id: "q5a",
        text: "Sehr empfindlich - ich brauche einen ruhigen Hund.",
        points: {
          borderCollie: 3,
          australianShepherd: 2,
          siberianHusky: 0,
          beagle: 0,
          pug: 4,
          cavalierKingCharles: 5,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 4,
          labradorRetriever: 3,
          irishWolfhound: 5,
          brusselsGriffon: 2,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q5b",
        text: "Etwas empfindlich - gelegentliches Bellen ist okay.",
        points: {
          borderCollie: 4,
          australianShepherd: 3,
          siberianHusky: 1,
          beagle: 1,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 5,
          labradorRetriever: 4,
          irishWolfhound: 5,
          brusselsGriffon: 3,
          bullTerrier: 4,
          cotonDeTulear: 5,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q5c",
        text: "Tolerant - ein bisschen Lärm gehört zum Hundeleben dazu.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 3,
          beagle: 4,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 3,
          labradorRetriever: 5,
          irishWolfhound: 3,
          brusselsGriffon: 5,
          bullTerrier: 5,
          cotonDeTulear: 3,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q5d",
        text: "Sehr tolerant - auch häufiges Bellen oder Heulen stört mich nicht.",
        points: {
          borderCollie: 3,
          australianShepherd: 4,
          siberianHusky: 5,
          beagle: 5,
          pug: 2,
          cavalierKingCharles: 2,
          shihTzu: 2,
          frenchBulldog: 2,
          goldenRetriever: 2,
          labradorRetriever: 3,
          irishWolfhound: 2,
          brusselsGriffon: 4,
          bullTerrier: 3,
          cotonDeTulear: 2,
          alaskanKleeKai: 4,
        },
      },
    ],
  },
  {
    id: "q6",
    text: "Hast du Kinder oder andere Haustiere?",
    answers: [
      {
        id: "q6a",
        text: "Ja, kleine Kinder (unter 6 Jahren).",
        points: {
          borderCollie: 3,
          australianShepherd: 2,
          siberianHusky: 2,
          beagle: 4,
          pug: 4,
          cavalierKingCharles: 5,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 3,
          brusselsGriffon: 2,
          bullTerrier: 2,
          cotonDeTulear: 4,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q6b",
        text: "Ja, ältere Kinder (über 6 Jahre).",
        points: {
          borderCollie: 5,
          australianShepherd: 4,
          siberianHusky: 4,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 4,
          brusselsGriffon: 3,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q6c",
        text: "Ja, Katzen oder andere kleine Haustiere.",
        points: {
          borderCollie: 4,
          australianShepherd: 3,
          siberianHusky: 1,
          beagle: 2,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 4,
          goldenRetriever: 5,
          labradorRetriever: 4,
          irishWolfhound: 3,
          brusselsGriffon: 4,
          bullTerrier: 2,
          cotonDeTulear: 5,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q6d",
        text: "Nein, weder Kinder noch andere Haustiere.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 5,
          brusselsGriffon: 5,
          bullTerrier: 5,
          cotonDeTulear: 5,
          alaskanKleeKai: 5,
        },
      },
    ],
  },
  {
    id: "q7",
    text: "Wie viel Zeit verbringst du normalerweise außer Haus?",
    answers: [
      {
        id: "q7a",
        text: "Ich bin den größten Teil des Tages zu Hause.",
        points: {
          borderCollie: 5,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 5,
          brusselsGriffon: 5,
          bullTerrier: 5,
          cotonDeTulear: 5,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q7b",
        text: "Ich bin etwa 4-6 Stunden täglich weg.",
        points: {
          borderCollie: 3,
          australianShepherd: 3,
          siberianHusky: 2,
          beagle: 3,
          pug: 4,
          cavalierKingCharles: 4,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 4,
          labradorRetriever: 4,
          irishWolfhound: 4,
          brusselsGriffon: 4,
          bullTerrier: 3,
          cotonDeTulear: 4,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q7c",
        text: "Ich bin etwa 8 Stunden täglich weg (typischer Arbeitstag).",
        points: {
          borderCollie: 1,
          australianShepherd: 1,
          siberianHusky: 1,
          beagle: 2,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 2,
          labradorRetriever: 2,
          irishWolfhound: 3,
          brusselsGriffon: 3,
          bullTerrier: 2,
          cotonDeTulear: 3,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q7d",
        text: "Ich bin oft mehr als 8 Stunden weg oder reise häufig.",
        points: {
          borderCollie: 0,
          australianShepherd: 0,
          siberianHusky: 0,
          beagle: 1,
          pug: 2,
          cavalierKingCharles: 2,
          shihTzu: 2,
          frenchBulldog: 2,
          goldenRetriever: 1,
          labradorRetriever: 1,
          irishWolfhound: 2,
          brusselsGriffon: 2,
          bullTerrier: 1,
          cotonDeTulear: 2,
          alaskanKleeKai: 1,
        },
      },
    ],
  },
  {
    id: "q8",
    text: "Wie wichtig ist dir ein Hund, der eng an dir hängt und dir überallhin folgt?",
    answers: [
      {
        id: "q8a",
        text: "Sehr wichtig - ich möchte einen Hund, der immer bei mir sein will.",
        points: {
          borderCollie: 5,
          australianShepherd: 4,
          siberianHusky: 2,
          beagle: 3,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 3,
          brusselsGriffon: 5,
          bullTerrier: 4,
          cotonDeTulear: 5,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q8b",
        text: "Wichtig - aber er sollte auch mal alleine sein können.",
        points: {
          borderCollie: 4,
          australianShepherd: 5,
          siberianHusky: 3,
          beagle: 5,
          pug: 4,
          cavalierKingCharles: 4,
          shihTzu: 4,
          frenchBulldog: 4,
          goldenRetriever: 4,
          labradorRetriever: 4,
          irishWolfhound: 4,
          brusselsGriffon: 4,
          bullTerrier: 5,
          cotonDeTulear: 4,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q8c",
        text: "Nicht so wichtig - ich schätze auch unabhängigere Hunde.",
        points: {
          borderCollie: 3,
          australianShepherd: 3,
          siberianHusky: 5,
          beagle: 4,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 5,
          brusselsGriffon: 3,
          bullTerrier: 3,
          cotonDeTulear: 3,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q8d",
        text: "Unwichtig - ich bevorzuge einen selbstständigen Hund.",
        points: {
          borderCollie: 1,
          australianShepherd: 2,
          siberianHusky: 5,
          beagle: 2,
          pug: 1,
          cavalierKingCharles: 1,
          shihTzu: 1,
          frenchBulldog: 1,
          goldenRetriever: 1,
          labradorRetriever: 1,
          irishWolfhound: 4,
          brusselsGriffon: 1,
          bullTerrier: 2,
          cotonDeTulear: 1,
          alaskanKleeKai: 4,
        },
      },
    ],
  },
  {
    id: "q9",
    text: "Wie wichtig ist dir die Größe des Hundes?",
    answers: [
      {
        id: "q9a",
        text: "Ich möchte einen kleinen Hund (unter 10 kg).",
        points: {
          borderCollie: 0,
          australianShepherd: 0,
          siberianHusky: 0,
          beagle: 3,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 5,
          goldenRetriever: 0,
          labradorRetriever: 0,
          irishWolfhound: 0,
          brusselsGriffon: 5,
          bullTerrier: 2,
          cotonDeTulear: 5,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q9b",
        text: "Ich bevorzuge einen mittelgroßen Hund (10-25 kg).",
        points: {
          borderCollie: 5,
          australianShepherd: 4,
          siberianHusky: 3,
          beagle: 5,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 2,
          frenchBulldog: 3,
          goldenRetriever: 2,
          labradorRetriever: 2,
          irishWolfhound: 0,
          brusselsGriffon: 1,
          bullTerrier: 5,
          cotonDeTulear: 1,
          alaskanKleeKai: 3,
        },
      },
      {
        id: "q9c",
        text: "Ich möchte einen großen Hund (25-45 kg).",
        points: {
          borderCollie: 3,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 1,
          pug: 0,
          cavalierKingCharles: 0,
          shihTzu: 0,
          frenchBulldog: 0,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 2,
          brusselsGriffon: 0,
          bullTerrier: 2,
          cotonDeTulear: 0,
          alaskanKleeKai: 0,
        },
      },
      {
        id: "q9d",
        text: "Ich bevorzuge einen sehr großen Hund (über 45 kg).",
        points: {
          borderCollie: 0,
          australianShepherd: 0,
          siberianHusky: 2,
          beagle: 0,
          pug: 0,
          cavalierKingCharles: 0,
          shihTzu: 0,
          frenchBulldog: 0,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 5,
          brusselsGriffon: 0,
          bullTerrier: 0,
          cotonDeTulear: 0,
          alaskanKleeKai: 0,
        },
      },
      {
        id: "q9e",
        text: "Die Größe ist mir nicht wichtig.",
        points: {
          borderCollie: 3,
          australianShepherd: 3,
          siberianHusky: 3,
          beagle: 3,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 3,
          brusselsGriffon: 3,
          bullTerrier: 3,
          cotonDeTulear: 3,
          alaskanKleeKai: 3,
        },
      },
    ],
  },
  {
    id: "q10",
    text: "Wie sollte dein idealer Hund auf Fremde reagieren?",
    answers: [
      {
        id: "q10a",
        text: "Freundlich und aufgeschlossen zu jedem.",
        points: {
          borderCollie: 3,
          australianShepherd: 2,
          siberianHusky: 3,
          beagle: 5,
          pug: 5,
          cavalierKingCharles: 5,
          shihTzu: 5,
          frenchBulldog: 4,
          goldenRetriever: 5,
          labradorRetriever: 5,
          irishWolfhound: 4,
          brusselsGriffon: 4,
          bullTerrier: 3,
          cotonDeTulear: 5,
          alaskanKleeKai: 2,
        },
      },
      {
        id: "q10b",
        text: "Anfangs zurückhaltend, aber dann freundlich.",
        points: {
          borderCollie: 5,
          australianShepherd: 4,
          siberianHusky: 4,
          beagle: 3,
          pug: 3,
          cavalierKingCharles: 3,
          shihTzu: 3,
          frenchBulldog: 3,
          goldenRetriever: 3,
          labradorRetriever: 3,
          irishWolfhound: 5,
          brusselsGriffon: 3,
          bullTerrier: 4,
          cotonDeTulear: 3,
          alaskanKleeKai: 4,
        },
      },
      {
        id: "q10c",
        text: "Reserviert und braucht Zeit, um aufzutauen.",
        points: {
          borderCollie: 3,
          australianShepherd: 5,
          siberianHusky: 3,
          beagle: 1,
          pug: 1,
          cavalierKingCharles: 1,
          shihTzu: 2,
          frenchBulldog: 2,
          goldenRetriever: 1,
          labradorRetriever: 1,
          irishWolfhound: 3,
          brusselsGriffon: 2,
          bullTerrier: 3,
          cotonDeTulear: 2,
          alaskanKleeKai: 5,
        },
      },
      {
        id: "q10d",
        text: "Wachsam und beschützend, ohne aggressiv zu sein.",
        points: {
          borderCollie: 4,
          australianShepherd: 5,
          siberianHusky: 5,
          beagle: 2,
          pug: 1,
          cavalierKingCharles: 1,
          shihTzu: 1,
          frenchBulldog: 3,
          goldenRetriever: 2,
          labradorRetriever: 2,
          irishWolfhound: 3,
          brusselsGriffon: 3,
          bullTerrier: 5,
          cotonDeTulear: 1,
          alaskanKleeKai: 4,
        },
      },
    ],
  },
];

export const dogBreedResults: Record<DogBreed, DogBreedResult> = {
  borderCollie: {
    id: "borderCollie",
    name: "Border Collie",
    description:
      "Border Collies sind hochintelligente, energiegeladene Arbeitshunde. Sie brauchen viel körperliche und geistige Stimulation und eignen sich am besten für aktive Menschen, die Zeit für Training und Aktivitäten haben. Ihre Intelligenz und Lernfähigkeit ist beeindruckend, aber sie brauchen eine Aufgabe, um glücklich zu sein.",
    image: "/images/dogs/border-collie.jpg",
    color: "bg-blue-700",
    size: "Mittelgroß (14-20 kg)",
    activityLevel: "Sehr hoch",
    groomingNeeds: "Mittel bis hoch",
    goodWith: ["Aktive Familien", "Kinder", "Andere Hunde"],
  },
  australianShepherd: {
    id: "australianShepherd",
    name: "Australian Shepherd",
    description:
      "Australian Shepherds sind vielseitige, energiegeladene Hunde mit starkem Arbeitstrieb. Sie sind intelligent, loyal und brauchen viel Bewegung und geistige Herausforderung. Mit ihrer freundlichen Art sind sie gute Familienhunde, benötigen aber konsequentes Training und viel Auslauf.",
    image: "/images/dogs/australian-shepherd.jpg",
    color: "bg-indigo-600",
    size: "Mittelgroß bis groß (16-32 kg)",
    activityLevel: "Sehr hoch",
    groomingNeeds: "Mittel bis hoch",
    goodWith: ["Aktive Familien", "Ältere Kinder", "Andere Hunde"],
  },
  siberianHusky: {
    id: "siberianHusky",
    name: "Siberian Husky",
    description:
      "Siberian Huskys sind unabhängige, energiegeladene Hunde mit einem freundlichen Wesen. Sie wurden zum Ziehen von Schlitten gezüchtet und haben einen starken Lauf- und Jagdtrieb. Sie sind gesellig, aber auch eigensinnig und brauchen viel Bewegung. Ihr dichtes Fell erfordert regelmäßige Pflege.",
    image: "/images/dogs/siberian-husky.jpg",
    color: "bg-gray-600",
    size: "Mittelgroß bis groß (16-27 kg)",
    activityLevel: "Sehr hoch",
    groomingNeeds: "Hoch",
    goodWith: ["Aktive Familien", "Ältere Kinder", "Andere Hunde"],
  },
  beagle: {
    id: "beagle",
    name: "Beagle",
    description:
      "Beagles sind freundliche, neugierige und fröhliche Hunde. Sie sind gute Familienhunde, die Gesellschaft lieben und gut mit Kindern auskommen. Ihr Jagdinstinkt kann sie manchmal ablenken, und sie können stur sein. Sie brauchen moderate Bewegung und sind für ihre Stimme bekannt.",
    image: "/images/dogs/beagle.jpg",
    color: "bg-amber-600",
    size: "Klein bis mittelgroß (9-11 kg)",
    activityLevel: "Mittel bis hoch",
    groomingNeeds: "Niedrig",
    goodWith: ["Familien", "Kinder", "Andere Hunde"],
  },
  pug: {
    id: "pug",
    name: "Mops",
    description:
      "Möpse sind liebevolle, verspielte und anhängliche Begleithunde. Sie sind ideal für Wohnungen und weniger aktive Haushalte. Mit ihrem charmanten Wesen und ihrer geringen Größe sind sie beliebte Familienhunde. Aufgrund ihrer kurzen Schnauze können sie bei Hitze und intensiver Aktivität Atemprobleme bekommen.",
    image: "/images/dogs/pug.jpg",
    color: "bg-yellow-700",
    size: "Klein (6-8 kg)",
    activityLevel: "Niedrig bis mittel",
    groomingNeeds: "Niedrig",
    goodWith: ["Familien", "Kinder", "Senioren", "Wohnungshaltung"],
  },
  cavalierKingCharles: {
    id: "cavalierKingCharles",
    name: "Cavalier King Charles Spaniel",
    description:
      "Cavalier King Charles Spaniels sind sanfte, liebevolle und anpassungsfähige Begleithunde. Sie sind ideal für Familien und Einzelpersonen jeden Alters. Mit ihrem freundlichen Wesen kommen sie gut mit Kindern und anderen Haustieren aus. Sie brauchen moderate Bewegung und regelmäßige Fellpflege.",
    image: "/images/dogs/cavalier-king-charles.jpg",
    color: "bg-red-600",
    size: "Klein (5-8 kg)",
    activityLevel: "Niedrig bis mittel",
    groomingNeeds: "Mittel",
    goodWith: ["Familien", "Kinder", "Senioren", "Andere Haustiere"],
  },
  shihTzu: {
    id: "shihTzu",
    name: "Shih Tzu",
    description:
      "Shih Tzus sind freundliche, liebevolle und selbstbewusste Begleithunde. Sie wurden als Gesellschaftshunde gezüchtet und lieben es, Zeit mit ihren Menschen zu verbringen. Ihr langes Fell erfordert regelmäßige Pflege, aber sie brauchen nur moderate Bewegung und eignen sich gut für Wohnungen.",
    image: "/images/dogs/shih-tzu.jpg",
    color: "bg-amber-800",
    size: "Klein (4-7 kg)",
    activityLevel: "Niedrig",
    groomingNeeds: "Hoch",
    goodWith: ["Familien", "Kinder", "Senioren", "Wohnungshaltung"],
  },
  frenchBulldog: {
    id: "frenchBulldog",
    name: "Französische Bulldogge",
    description:
      "Französische Bulldoggen sind verspielte, liebevolle und anpassungsfähige Begleithunde. Mit ihrem kompakten Körperbau und ihrem minimalen Bewegungsbedarf eignen sie sich gut für Wohnungen. Sie sind freundlich zu Fremden und anderen Haustieren, können aber stur sein. Aufgrund ihrer kurzen Schnauze können sie bei Hitze Probleme haben.",
    image: "/images/dogs/french-bulldog.jpg",
    color: "bg-gray-700",
    size: "Klein (8-14 kg)",
    activityLevel: "Niedrig",
    groomingNeeds: "Niedrig",
    goodWith: ["Familien", "Kinder", "Senioren", "Wohnungshaltung"],
  },
  goldenRetriever: {
    id: "goldenRetriever",
    name: "Golden Retriever",
    description:
      "Golden Retriever sind freundliche, intelligente und treue Familienhunde. Sie sind bekannt für ihre Geduld und Sanftmut, besonders mit Kindern. Sie brauchen regelmäßige Bewegung und geistige Stimulation. Ihr dichtes Fell erfordert regelmäßige Pflege, aber ihr liebevolles Wesen macht sie zu idealen Begleitern.",
    image: "/images/dogs/golden-retriever.jpg",
    color: "bg-yellow-600",
    size: "Groß (25-34 kg)",
    activityLevel: "Mittel bis hoch",
    groomingNeeds: "Mittel",
    goodWith: ["Familien", "Kinder", "Andere Haustiere"],
  },
  labradorRetriever: {
    id: "labradorRetriever",
    name: "Labrador Retriever",
    description:
      "Labrador Retriever sind freundliche, aktive und vielseitige Familienhunde. Sie sind intelligent, leicht zu trainieren und kommen gut mit Kindern und anderen Haustieren aus. Sie brauchen regelmäßige Bewegung und geistige Stimulation. Mit ihrem ausgeglichenen Wesen sind sie ideale Begleiter für aktive Familien.",
    image: "/images/dogs/labrador-retriever.jpg",
    color: "bg-yellow-800",
    size: "Groß (25-36 kg)",
    activityLevel: "Hoch",
    groomingNeeds: "Niedrig bis mittel",
    goodWith: ["Familien", "Kinder", "Andere Haustiere"],
  },
  irishWolfhound: {
    id: "irishWolfhound",
    name: "Irischer Wolfshund",
    description:
      "Irische Wolfshunde sind sanfte Riesen mit ruhigem und freundlichem Wesen. Trotz ihrer Größe sind sie relativ ruhig im Haus, brauchen aber regelmäßige Bewegung. Sie sind loyal und liebevoll zu ihren Familien, aber aufgrund ihrer Größe nicht für kleine Wohnungen geeignet. Ihre Lebenserwartung ist leider kürzer als bei kleineren Rassen.",
    image: "/images/dogs/irish-wolfhound.jpg",
    color: "bg-gray-500",
    size: "Sehr groß (40-70 kg)",
    activityLevel: "Mittel",
    groomingNeeds: "Mittel",
    goodWith: ["Familien mit Platz", "Ältere Kinder"],
  },
  brusselsGriffon: {
    id: "brusselsGriffon",
    name: "Brüsseler Griffon",
    description:
      "Brüsseler Griffons sind selbstbewusste, neugierige und anhängliche kleine Hunde. Sie haben einen ausgeprägten Charakter und sind sehr menschenbezogen. Trotz ihrer geringen Größe sind sie mutig und wachsam. Sie eignen sich gut für Wohnungen, brauchen aber geistige Stimulation und moderate Bewegung.",
    image: "/images/dogs/brussels-griffon.jpg",
    color: "bg-red-700",
    size: "Sehr klein (2,5-5 kg)",
    activityLevel: "Mittel",
    groomingNeeds: "Mittel bis hoch",
    goodWith: ["Familien", "Senioren", "Wohnungshaltung"],
  },
  bullTerrier: {
    id: "bullTerrier",
    name: "Bull Terrier",
    description:
      "Bull Terrier sind verspielte, energiegeladene und liebevolle Hunde mit einem einzigartigen Aussehen. Sie sind loyal und beschützend gegenüber ihren Familien, brauchen aber konsequentes Training und Sozialisierung. Mit ihrem starken Charakter sind sie nicht für Anfänger geeignet, aber für erfahrene Hundehalter wunderbare Begleiter.",
    image: "/images/dogs/bull-terrier.jpg",
    color: "bg-gray-200",
    size: "Mittelgroß (22-38 kg)",
    activityLevel: "Hoch",
    groomingNeeds: "Niedrig",
    goodWith: ["Erfahrene Hundehalter", "Aktive Familien", "Ältere Kinder"],
  },
  cotonDeTulear: {
    id: "cotonDeTulear",
    name: "Coton de Tuléar",
    description:
      "Coton de Tuléars sind fröhliche, anhängliche und anpassungsfähige Begleithunde. Mit ihrem weichen, baumwollartigen Fell und ihrem liebevollen Wesen sind sie ideale Familienhunde. Sie sind intelligent und trainierbar, brauchen aber regelmäßige Fellpflege. Sie kommen gut mit Kindern und anderen Haustieren aus.",
    image: "/images/dogs/coton-de-tulear.jpg",
    color: "bg-blue-100",
    size: "Klein (4-6 kg)",
    activityLevel: "Niedrig bis mittel",
    groomingNeeds: "Hoch",
    goodWith: ["Familien", "Kinder", "Senioren", "Andere Haustiere"],
  },
  alaskanKleeKai: {
    id: "alaskanKleeKai",
    name: "Alaskan Klee Kai",
    description:
      "Alaskan Klee Kais sind intelligente, energiegeladene und wachsame kleine Hunde, die wie Miniatur-Huskys aussehen. Sie sind loyal zu ihren Familien, aber können Fremden gegenüber zurückhaltend sein. Sie brauchen regelmäßige Bewegung und geistige Stimulation. Mit ihrem ausgeprägten Jagdtrieb sollten sie an der Leine geführt werden.",
    image: "/images/dogs/alaskan-klee-kai.jpg",
    color: "bg-blue-800",
    size: "Klein (4-10 kg)",
    activityLevel: "Hoch",
    groomingNeeds: "Mittel",
    goodWith: ["Aktive Familien", "Ältere Kinder", "Erfahrene Hundehalter"],
  },
};
